loaders/examples.loader.js, src/components/Playground/Playground.js, src/components/Preview/Preview.js, src/components/ReactComponent/ReactComponent.js, test/examples.loader.spec.js
@sapegin, I need your help with testing this code. And I wait for any other comments. ;)
=> Added support for using require(...) in code examples.

src/rsg-components/Props/Props.js
Support for flow type annotations is coming to react-docgen via https://github.com/reactjs/react-docgen/pull/48 (note: PR is not yet merged but works locally and looks ready)
With this PR, the styleguide will use the flow annotation if it is present, and fall back to the `propType` if it isn't.
The syntax looks like this:
```js
type Props = {
/* The title of the box */
title: string;
}
class Box extends React.Component {
props: Props;
render (): React.Element {
return <h1>{this.props.title}</h1>;
}
}
```
=> Support flow annotations for prop types

package.json
=> Bump react-docgen to 2.7.0 to support flow proptypes

Readme.md, src/rsg-components/Props/Props.js, test/components.props.spec.js
Fixes #77.
This ensures that any prop that is assigned via `getDefaultProps` but missing from `propTypes` will be shown as an unknown prop type.
Although this is bad practice in React, I think it's probably best to display the style guide rather than throw and error for this, and ensure that the user can find out the explanation behind unknown proptypes in the styleguide readme.
=> Handle unknown proptypes

Readme.md
As it says in the PR title. There was a lot of inconsistency in the readme between "style guide" and "styleguide". This ensures that they all use "style guide" where applicable. This does not touch filenames, paths, or options within the readme.
=> Ensures styleguide is always 'style guide' in readme

examples/customised/styleguide/components/Layout/Layout.css, examples/customised/styleguide/components/Layout/index.jsx, package.json, src/rsg-components/Layout/Layout.css, src/rsg-components/Layout/Renderer.jsx, src/rsg-components/TableOfContents/TableOfContents.css
**This PR makes some layout and style changes to the default style guide output**
My existing codebase has a large number of components, running styleguidist on this results in a list of components that is not scrollable do the "sticky" functionality that currently exists.
This PR makes changes to the layout to ensure that the component list is always scrollable. The component list has been moved to the left of the screen due to the fact that there is a max-width on the styleguide(which i think is important) and implementing scrolling functionality with that given layout felt odd. It wasn't clear that you could scroll the components list, this approach goes for something a little more "traditional" as far as documentation styling goes.
=> Ensure components list is scrollable

src/rsg-components/Props/Props.css, src/rsg-components/Props/Props.js, test/components.props.spec.js
Maybe this is just a nitpick from my side, but I think it would be better to explicitly specify it when a prop is required. This way a developer does not overlook your prop requirement that easy.
I'm curious what you think about this change :smile:.
=> Explicitly specify when a prop is required

Readme.md, loaders/props.loader.js, src/index.js, src/utils/utils.js
This PR introduces the ability to associate additional example files using doclet tags in the description.
For example, a component defined like the below will have the examples in `extra.examples.md` associated with it:
```js
/**
* Component is described here.
*
* @example ./extra.examples.md
*/
export default class SomeComponent extends React.Component {
// ...
}
=> Example Doclets

Readme.md, loaders/styleguide.loader.js, src/index.js, src/rsg-components/Components/Components.js, src/rsg-components/Layout/Layout.js, src/rsg-components/Section/Renderer.jsx, src/rsg-components/Section/Section.css, src/rsg-components/Section/Section.js, src/rsg-components/Section/index.js, src/rsg-components/Sections/Sections.js, src/rsg-components/Sections/index.js, src/rsg-components/TableOfContents/TableOfContents.js, src/utils/config.js
This PR introduces the ability to split components into sections. Sections are configured in the `styleguide.config.js` file as a peer to the main `components` property. Sections can be nested if desired, since they are processed recursively. Sections can also include a reference to a `content` examples file that is used an introduction to the section.
Support for non-sectioned components is retained, so this PR should have no effect on existing guides that don't configure sections.
=> Support for creating Sections

Readme.md, loaders/props.loader.js
I want to override default parser. Ref: #117
=> Custom props parser support

examples/basic-sections/Readme.md, examples/basic-sections/lib/components/Button/Button.css, examples/basic-sections/lib/components/Button/Button.js, examples/basic-sections/lib/components/Button/Readme.md, examples/basic-sections/lib/components/Button/index.js, examples/basic-sections/lib/components/Modal/Modal.js, examples/basic-sections/lib/components/Modal/Readme.md, examples/basic-sections/lib/components/Modal/index.js, examples/basic-sections/lib/components/Placeholder/Placeholder.css, examples/basic-sections/lib/components/Placeholder/Placeholder.js, examples/basic-sections/lib/components/Placeholder/Readme.md, examples/basic-sections/lib/components/Placeholder/index.js, examples/basic-sections/lib/components/RandomButton/RandomButton.css, examples/basic-sections/lib/components/RandomButton/RandomButton.js, examples/basic-sections/lib/components/RandomButton/Readme.md, examples/basic-sections/lib/components/RandomButton/index.js, examples/basic-sections/styleguide.config.js, examples/basic-sections/styleguide/CNAME, package.json, src/index.js
This fixes issues introduced by the merge of #108 in to master.
Both @paulj and @sapegin may have some ideas on the changes to `index.js` here, but this ensures that sections not being provided will not break the styleguide. There were issues with running examples as a result of this merge.
This also adds a basic example using sections for testing this new feature.
=> Ensure lack of sections does not break styleguide and update examples

src/rsg-components/Section/Section.css
Takes some styling from the existing ReactComponent headings and ensures that sections do not use Times New Roman and look out of place.
=> Add basic styling for section headings

package.json, src/index.js, src/rsg-components/Layout/Layout.css, src/rsg-components/Layout/Layout.js, src/rsg-components/Layout/Renderer.jsx
**This is part of an ongoing project to look at speeding up webpack, as well as speeding up the development within styleguide driven development**
This has been mentioned in #98 and is something my team has struggled with as we look to use this library for styleguide driven development.
Currently, when using the styleguide and hot reload functionality to develop new components, or modify existing components, there is an issue with scroll position due to loading of code previews and rendered components between page reloads.
Although this could be solved with some extra functionality around page load and ensuring the page is scrolled to the correct position, our team decided that having a simple solution for viewing a single component on the page would be more beneficial. This PR includes …
=> Single Component View

loaders/props.loader.js
This avoid "Error when parsing index.js" and offer a better filename like "Error when parsing web_modules/SidebarItem/index.js".
=> More accurate filename in case of error when parsing component

src/rsg-components/Editor/Editor.js
Fixes https://github.com/sapegin/react-styleguidist/issues/139
The reason why this happens is because the `<Editor />` component re-renders when code changes by the editor itself. So when the `handleChange()` event is fired, it's re-rendering the `<Editor />` which resets where the cursor position is.
There's 2 ways to fix this. One way is to capture the current cursor position in `componentWillReceiveProps()` and then set it again in `componentDidUpdate()`, but that's a bit hacky and a lot of machinery for no real reason.
The other, and I think simpler approach (and what is implemented in this PR), is to just not have the `<Editor />`  update once it's been rendered, so it no longer reacts to property updates entirely. This is okay because we just need the codemirror editor rendered once …
=> Fix cursor jumping while editing in codemirror

.gitignore, docs/Configuration.md, loaders/styleguide.loader.js, src/rsg-components/Components/Components.js, src/rsg-components/Layout/Layout.js, src/rsg-components/Layout/Renderer.jsx, src/rsg-components/Playground/Playground.css, src/rsg-components/Playground/Playground.js, src/rsg-components/ReactComponent/ReactComponent.js, src/rsg-components/ReactComponent/Renderer.jsx, src/rsg-components/Section/Renderer.jsx, src/utils/config.js
Adds the ability to toggle the CodeMirror box:
This _may_ help address https://github.com/sapegin/react-styleguidist/issues/86 but I'm actually not sure of the performance gains because I do not have a large testcase like the one in that issue. Below is the timeline for the basic example in the repo. You can see that rendering has improved and I imagine on a larger example case it could make a dramatic benefit. Either way, you can see that the 'Scripting' time is the big time suck, but that's a whole different story for another PR.
*Before*
*After*
I've also just done a very simple `if (showCode) { ... }` check, so not sure if there's an even more effective way to gain a performance boost by doing it another way or not, but at least it's a start.
It defaults to `showCode: false` in this …
=> Add code toggleability

docs/GettingStarted.md, loaders/examples.loader.js
Markdown fenced code blocks without a syntax prevent text editors from enabling syntax features within the code block.
This change allows fenced code blocks with `jsx` syntax to render the same as without a syntax specified.
=> Allow markdown ```example to render interactive example.

src/make-webpack-config.js
Hi!
Build styleguide from Webpack 2 not work.
This occurs because of an error in the name of the plugin OccurrenceOrderPlugin.
Relative link https://github.com/webpack/webpack/issues/1964
=> Fix name plugin OccurrenceOrderPlugin

loaders/props.loader.js
Hi!
The `file` variable should be set outside of the `try` statement because it is used in the `catch` error reporting. So when there's an error parsing a file I will only get:
```
ERROR in ./~/react-styleguidist/loaders/props.loader.js!./src/components/modal/prompt/Prompt.js
Module build failed: ReferenceError: file is not defined
at Object.module.exports (/Users/adrien/Projects/dev-setup/tray/src/github.com/trayio/react-ui/node_modules/react-styleguidist/loaders/props.loader.js:41:66)
@ ./~/react-styleguidist/loaders/styleguide.loader.js! 4:19905-20030
@ ./~/react-styleguidist/src/index.js
@ multi main
```
and after this fix I get the right error message:
```
Error when parsing src/components/modal/prompt/Prompt.js
Error: No suitable component definition found.
```
=> Fixed error reporting showing 'file is not defined'

docs/Configuration.md, docs/FAQ.md, src/server.js
I want to be able to manage what is the output of dev server. I think passing `webpack.stats` options to dev middleware is a good way. What do you think?
=> Expose webpack stats config on webpack dev middleware

docs/Readme.md
Looks like a simple copy/paste error from this readme being in root.
=> docs/Readme.md had invalid link paths.

package.json
Hi! Thank you for awesome styleguide.
I'm using the Intersection types of flowtype.
At that time the following errors occurred.
```bash
ERROR in ./~/react-styleguidist/loaders/props.loader.js!./src/js/components/ui/IconButton/IconButton.js
Module build failed: ReferenceError: file is not defined
at Object.module.exports (/Applications/XAMPP/xamppfiles/htdocs/flamber/node_modules/react-styleguidist/loaders/props.loader.js:40:66)
@ ./~/react-styleguidist/loaders/styleguide.loader.js! 4:14908-15018
ERROR in ./~/react-styleguidist/loaders/props.loader.js!./src/js/components/ui/StarButton/StarButton.js
Module build failed: ReferenceError: file is not defined
at Object.module.exports (/Applications/XAMPP/xamppfiles/htdocs/flamber/node_modules/react-styleguidist/loaders/props.loader.js:40:66)
@ …
```
=> Update react-docgen version

src/rsg-components/Props/PropsRenderer.js, src/rsg-components/Props/util.js
=> Show whitespace character for default values

package.json, src/rsg-components/Props/Props.css, src/rsg-components/Props/Props.spec.js, src/rsg-components/Props/PropsRenderer.js, src/rsg-components/Props/util.js
This PR closes #194. It replaces li/ul tags with `react-group` package and simplifies `renderDescription`. The specs were fixed to reflect this changes.
=> Refactoring: simplify PropsRenderer a bit

src/index.js, src/rsg-components/Components/Components.js, src/rsg-components/Examples/Examples.js, src/rsg-components/Examples/Examples.spec.js, src/rsg-components/Playground/Playground.css, src/rsg-components/Playground/Playground.js, src/rsg-components/Playground/Playground.spec.js, src/rsg-components/Playground/PlaygroundRenderer.js, src/rsg-components/ReactComponent/ReactComponent.js, src/rsg-components/StyleGuide/StyleGuide.js, src/utils/utils.js, test/utils.utils.spec.js
Hi @sapegin 
first of all thanks for this project! I really love it and we use it in several projects.
In many of our library projects is the only available compiled output  and we often need to isolate a single example from a readme file.
This PR add the ability to isolate a single code example to simplify the development process.
Would you like to add this feature to the official repo? 
I'd love to have your feedback!
Cheers
=> Enable isolation of a single fenced block example

docs/Configuration.md, loaders/styleguide.loader.js, scripts/config.js, src/rsg-components/Playground/Playground.js
This is something I've often loved to have using `react-styleguidist`. Basically it enables to write code in codemirror without having tens of updates on the preview panel. As side-effect is also less probable that while writing the preview will crash because of incomplete expressions.
Is this something you'd like to add to the project?
=> Added config to debounce preview rendering while live editing

src/rsg-components/Playground/Playground.css
If a component has `float: left` (or another float) in styles, current `.ReactStyleguidist-Playground__preview` container does not give it enough space to be rendered. With `overflow: auto` I can ensure that the container's height is enough.
=> Preview container to overflow the floating components

.gitignore, src/rsg-components/Playground/PlaygroundRenderer.js, src/rsg-components/ReactComponent/ReactComponentRenderer.js
=> Add extra HTML markup to make previews easier to find with CSS selectors

src/rsg-components/ComponentsList/ComponentsList.css, src/rsg-components/ComponentsList/ComponentsListRenderer.js, src/rsg-components/StyleGuide/StyleGuide.css, src/rsg-components/TableOfContents/TableOfContents.css
On screens narrower than 600px the sidebar will be moved to the top of the page and displayed as a static element to allow content column to take up all of the space.
=> Add mobile styles to improve display on narrow screens

examples/customised/styleguide.config.js, examples/customised/styleguide/components/ReactComponent/ReactComponent.css
This PR fixes two issues with `customised` example:
- wrong path to components (so running `npm run start:customised` doesn't show a "no components found" page)
- unrestricted width of component path string (so the headers and prop tables don't get wider than the enclosing container, [before](https://cloud.githubusercontent.com/assets/632081/20463341/6d95d4b6-af6b-11e6-8c97-f9ae3341f1bd.png)/[after](https://cloud.githubusercontent.com/assets/632081/20463344/7354c114-af6b-11e6-93e9-e3dd63889197.png))
=> Fix path and styles in "customised" example

src/rsg-components/StyleGuide/StyleGuide.js
There is a search field on the "no components found" page (can be encountered in `customised` example before [PR #246](https://github.com/styleguidist/react-styleguidist/pull/246) It is lonely and somewhat useless, and probably shouldn't be there in the first place.
=> Don't display sidebar and search field if there are no components found

docs/GettingStarted.md
Trying to rely on object references in the examples will not work.
@see #261
=> docs(GettingStarted): state object reference behaviour caveat

examples/basic/package.json, examples/customised/package.json, examples/sections/package.json
Decided to add webpack as dependency for examples, since it is a peer dependency for styleguidist now. Easier to install everything in one go.
Also bumped up other deps, everything seems working correctly.
=> Update examples deps, add webpack as dep

examples/basic/lib/components/Button/Button.js, examples/basic/lib/components/Modal/Modal.js, examples/basic/lib/components/Placeholder/Placeholder.js, examples/basic/lib/components/PushButton/PushButton.js, examples/basic/lib/components/WrappedButton/WrappedButton.js, examples/customised/lib/components/Button/Button.js, examples/customised/lib/components/Modal/Modal.js, examples/customised/lib/components/Placeholder/Placeholder.js, examples/sections/lib/components/Button/Button.js, examples/sections/lib/components/Modal/Modal.js, examples/sections/lib/components/Placeholder/Placeholder.js, loaders/utils/chunkify.js, loaders/utils/getRequires.js, src/rsg-components/Preview/Preview.js, src/rsg-components/Props/Props.spec.js, src/rsg-components/Props/PropsRenderer.js, src/utils/markdown-to-jsx.js, src/utils/utils.js, test/components/Button/Button.js, test/components/Placeholder/Placeholder.js, test/loader.examples.spec.js, test/utils.utils.spec.js
Running `npm test` or `npm run lint` shows a bunch of "prefer-const" errors:
.../react-styleguidist/examples/basic/lib/components/Placeholder/Placeholder.js
22:9   error  'type' is never reassigned. Use 'const' instead    prefer-const
22:15  error  'width' is never reassigned. Use 'const' instead   prefer-const
22:22  error  'height' is never reassigned. Use 'const' instead  prefer-const
...etc
This PR fixes these errors.
=> Fix eslint errors

Readme.md
The link was pointing to the old location :+1:
=> Fix "Basic style guide"-link in Readme.md

src/rsg-components/Playground/Playground.css
The border around the show/hide code area doesn't quite line up with the border around the component in Safari on Mac OS 10.12.1. Fixed by adding margin: 0 to button.
=> Fix: Style update to code toggle button

docs/FAQ.md, examples/basic/lib/components/CounterButton/CounterButton.css, examples/basic/lib/components/CounterButton/CounterButton.js, examples/basic/lib/components/CounterButton/Readme.md, examples/basic/lib/components/CounterButton/index.js, loaders/props.loader.js, src/rsg-components/Methods/Methods.css, src/rsg-components/Methods/Methods.spec.js, src/rsg-components/Methods/MethodsRenderer.js, src/rsg-components/Methods/index.js, src/rsg-components/ReactComponent/ReactComponent.css, src/rsg-components/ReactComponent/ReactComponent.js, src/rsg-components/ReactComponent/ReactComponentRenderer.js
This change adds (basic) support for documenting public methods of components using jsdoc tags `@public`, `@param` and `@returns`.
=> Publish public methods

src/rsg-components/ReactComponent/ReactComponent.spec.js, src/rsg-components/ReactComponent/ReactComponentRenderer.js, src/rsg-components/ReactComponent/__snapshots__/ReactComponent.spec.js.snap
Using Boolean expression as for props. Prior method was rendering `false` which isn't a valid React node value.
+ Add tests for methods section.
=> style: Use same code style to render `null` value

docs/Configuration.md, loaders/styleguide-loader.js, scripts/schemas/config.js, src/index.js, src/rsg-components/Components/Components.js, src/rsg-components/Examples/Examples.spec.js, src/rsg-components/Playground/Playground.js, src/rsg-components/Playground/PlaygroundRenderer.js, src/rsg-components/ReactComponent/ReactComponent.js, src/rsg-components/ReactComponent/ReactComponent.spec.js, src/rsg-components/ReactComponent/ReactComponentRenderer.js, src/rsg-components/ReactComponent/__snapshots__/ReactComponent.spec.js.snap, src/rsg-components/Section/Section.js, src/rsg-components/Sections/Sections.js, src/rsg-components/StyleGuide/StyleGuide.js, src/rsg-components/StyleGuide/StyleGuide.spec.js, src/rsg-components/StyleGuide/StyleGuideRenderer.js, src/rsg-components/StyleGuide/__snapshots__/StyleGuide.spec.js.snap
This PR adds a new configuration option `showSidebar`. If set to `false` sidebar will never appear. By default it is set to `true` to preserve the original behavior.
Additionally, this PR refactors:
1. Use context instead of passing down `isolatedComponent` prop
1. Use less ambiguous variable names: 
- `sidebar` -> `isolatedComponent`
- `sidebar` -> `hasSidebar`
- `singleExample` -> `isolatedExample`
=> Feat: Add showSidebar config option

Readme.md, docs/CLI.md, docs/Components.md, docs/Configuration.md, docs/Documenting.md, docs/Webpack.md
This PR cleans up grammar and fixes a few typos in the docs.
=> Minor documentation fixes

examples/sections/docs/Two.md, src/rsg-components/Examples/Examples.js, src/rsg-components/Examples/__snapshots__/Examples.spec.js.snap, src/rsg-components/Markdown/Markdown.js, src/rsg-components/Markdown/Markdown.spec.js, src/rsg-components/Markdown/__snapshots__/Markdown.spec.js.snap, src/rsg-components/Sections/SectionsRenderer.js, src/rsg-components/Sections/__snapshots__/Sections.spec.js.snap, src/utils/markdown-to-jsx.js
Current version renders `<h3>` instead of `<h1>` for the following snippet `# Heading`. 
According to W3C this is the desired approach for outlining structure in HTML5: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines
This PR eliminated altering of markdown headings and uses more HTML5 compliant markup with `<article>` for markdown documents.
=> Fix markdown headings

src/rsg-components/Playground/PlaygroundRenderer.js, src/rsg-components/Playground/__snapshots__/Playground.spec.js.snap
=> Replace static CSS class with a data attribute on Preview

src/rsg-components/Props/Props.spec.js, src/rsg-components/Props/PropsRenderer.js, src/rsg-components/Props/__snapshots__/Props.spec.js.snap
This PR improves support for objectOf propType by displaying the name of the type of values and, in case of objectOf(shape), displaying the properties of the shape.
=> Improve support for objectOf propType

src/rsg-components/ComponentsList/ComponentsListRenderer.js
This PR adds a little bit of extra styling to improve display of very long component names in the sidebar.
Before:
After:
=> Better display of very long component names in the sidebar

src/rsg-components/StyleGuide/StyleGuideRenderer.js
This PR adds a little bit of padding to the sidebar to "unglue" menu items off the bottom of the document on small screens.
Before:
After:
=> Slight improvement to sidebar styling on small screens

docs/Cookbook.md
While I was checking out the new cookbook(btw this new version is amazing) I realized that https://github.com/styleguidist/react-styleguidist/blob/master/docs/Cookbook.md#how-to-change-the-layout-of-a-style-guide is using `sidebar` prop instead `hasSidebar`. I'm fixing that because I feel is confusing have a example with the wrong prop. So:
**Before**
```javascript
// lib/styleguide/StyleGuideRenderer.js
import React from 'react';
const StyleGuideRenderer = ({ title, homepageUrl, components, toc, sidebar }) => (
<div className="root">
<h1>{title}</h1>
<main className="wrapper">
<div className="content">
{components}
<footer className="footer">
<Markdown text={`Generated with [React Styleguidist](${homepageUrl})`} />
</footer>
</div>
{sidebar &&
<div className="sidebar">
{toc}
</div>
} …
```
=> Replacing hasSidebar instead of sidebar in Cookbox

docs/Configuration.md, scripts/schemas/config.js
This allows users to connect from outside their local machines
Resolves #373
=> Change default serverHost to 0.0.0.0

docs/Configuration.md, loaders/props-loader.js
In examples i see that default propsParser is require('react-doc-gen').parse(content);
but here i see that you passed config.resolver, config.handlers(file) to docGen.
Now i need to call react-doc-gen in my custom propsParser, but i havent access to handlers and resolver.
=> pass resolver and handlers to propsParser

scripts/__tests__/create-server.spec.js, scripts/__tests__/index.spec.js, scripts/make-webpack-config.js
If you try to build a project with multiple entries without this, you get an error about multiple entries being written to `build/bundle.js`.
While there may be something to be said about not having multiple entrypoints in a dev build, this should have zero impact on any project without multiple entries. And since `output` can't be changed with the config's `webpackConfig` option, the only other way is to use `dangerouslyUpdateWebpackConfig`, which I'd rather avoid.
=> Use `[name]` in output filename

docs/Configuration.md, loaders/styleguide-loader.js, scripts/schemas/config.js, src/rsg-components/Preview/Preview.js, src/rsg-components/Preview/Preview.spec.js
Allows for configuration of buble. Needed this for my use case so that my code examples could have tagged template literals. In buble the config is `transforms.dangerousTaggedTemplateString`
=> Add buble configuration option

docs/Components.md, docs/Configuration.md, scripts/schemas/config.js
Some style guides, require you to change the extension of files containing JSX to .jsx. So, I think it would be good if `styleguide server` also ignore files named .spec.jsx and .test.jsx.
=> Support .jsx by default

scripts/create-server.js
With this PR, users will be able to pass custom configuration to webpack-dev-server during development. In particular, it will allow setting `disableHostCheck: true` to work around https://github.com/webpack/webpack-dev-server/issues/882
=> Pass devServer configuration to webpack-dev-server

package.json
This PR rolls markdown-to-jsx back to 5.2.0 to fix #413
=> Roll back to markdown-to-jsx 5.2.0

package.json, src/rsg-components/Editor/EditorLoaderRenderer.js, src/rsg-components/Playground/Playground.spec.js, src/styles/setupjss.js, src/styles/styles.js, yarn.lock
Here is a starting point for allowing the themed monospace font to be used by CodeMirror. Because CodeMirror css is global it used jss-global.
=> Use jss-global to target CodeMirror styles while still allowing theming

package.json
The issue with markdown-to-jsx 5.3.0 appears to be fixed in 5.3.2 (https://github.com/probablyup/markdown-to-jsx/pull/105), so I'm reverting my previous change
Fixes #413 (again)
=> Roll forward to markdown-to-jsx 5.3.0

docs/Cookbook.md
I found a way to put `Relay.createContainer`-wrapped components into Styleguide, and I thought I'd share.
=> Add Relay to the cookbook

docs/Cookbook.md
Hello!
I found a little mistake IMO. The note after `styled-components` question said:
> **Note:** to change style guide styles use `theme` and `styles` options (see the next question).
But the next question is about `Preact` and the question right after is exactly about `theme` and `styles`. So I changed the order to match "note" in `styled-components` question.
Thank you for the project!
Best,
Nikolay.
=> Docs: Fix question order in Cookbook

src/rsg-components/Preview/Preview.js
This change makes easier debugging.
Before this change you can't understand why and how did you get an error
After merge, developer would be able to discover errors in console:
=> Add logging for handled errors in Preview

examples/basic/src/components/Button/Button.js, loaders/utils/__tests__/__snapshots__/getProps.spec.js.snap, loaders/utils/__tests__/getProps.spec.js, loaders/utils/getProps.js
This pull request fixes a crash, that occurs when you use a defaultProp that is not listed in the props. The cause was my previous PR not checking whether the incoming description might be `undefined`.
The error is kind of nasty because the styleguidist wont compile. 
I added the fix and the test to replicate the error.
=> Fixes a crash when using a defaultProp that is not listed in props

package.json, src/rsg-components/Playground/PlaygroundRenderer.js, src/rsg-components/Playground/__snapshots__/Playground.spec.js.snap, src/rsg-components/ReactComponent/ReactComponentRenderer.js, src/rsg-components/ReactComponent/__snapshots__/ReactComponent.spec.js.snap
- Removes open isolated from preview
Fixes #235
=> fix(235) - Move open isolated

src/rsg-components/ReactComponent/ReactComponentRenderer.js, src/rsg-components/ReactComponent/__snapshots__/ReactComponent.spec.js.snap, src/rsg-components/Section/SectionRenderer.js
Hello @sapegin.
Minor fix for situation when you docs published not in root of domain.
for example when your docs build at https://alfa-laboratory.github.io/arui-feather/arui-demo/styleguide url for isolated component is https://alfa-laboratory.github.io/arui-feather/arui-demo/styleguide/#!/Amount
"Back" button navigates to https://alfa-laboratory.github.io/
=> fix(*): fix back button path for support pathname-relative paths

src/rsg-components/Text/Text.spec.js, src/rsg-components/Text/TextRenderer.js, src/rsg-components/Text/__snapshots__/Text.spec.js.snap
This PR restores the popup which described function text for functions as default props.
=> Fix missing title in function descriptions

src/rsg-components/TabButton/TabButtonRenderer.js
This PR explicitly removes border from TabButton to make it look good on Windows.
=> Remove border from TabButton

scripts/make-webpack-config.js
`react-styleguidist` seems to have an incompatibility with Webpack 3 ([released today](https://github.com/webpack/webpack/releases/tag/v3.0.0)). Specifically, the issue I experienced was that the Webpack config used with Webpack 3 had its `config.resolve.extensions` [set to](https://github.com/styleguidist/react-styleguidist/blob/master/scripts/make-webpack-config.js#L32) `['.js', '.jsx', '.json', '']` (which Webpack 3 complains about):
```
$ ./node_modules/.bin/styleguidist server --config ./node_modules/js-infra/config/styleguidist/index.js
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
- configuration.resolve.extensions[3] should not be empty.
```
I've tried tweaking the Webpack 2 conditions in …
=> Tweak Webpack 2 conditions

docs/Configuration.md, docs/Cookbook.md, docs/Development.md, examples/customised/styleguide.config.js, scripts/__tests__/index.spec.js, scripts/make-webpack-config.js, scripts/schemas/config.js
Implements #483.
/cc @bluetidepro
=> Feat: New config option styleguideComponents

src/rsg-components/TableOfContents/TableOfContentsRenderer.js
=> Isolate search placeholder styles

examples/webpack/package.json, examples/webpack/webpack.config.js
When trying to run this example I was getting an error because of `.babelrc` defined in the root folder of the project. 
Error before the change:
```bash
Hash: 433f7d975abbc65d5e0e
Version: webpack 2.6.1
Time: 503ms
Asset     Size  Chunks             Chunk Names
bundle.js  4.38 kB       0  [emitted]  main
[0] ./src/index.js 1.74 kB {0} [built] [failed] [1 error]
ERROR in ./src/index.js
Module build failed: ReferenceError: Unknown plugin "transform-class-properties" specified in "/Users/cristian.oliveira/other/react-styleguidist/.babelrc" at 0, attempted to resolve relative to "/Users/cristian.oliveira/other/react-styleguidist"
at /Users/cristian.oliveira/other/react-styleguidist/examples/webpack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
at Array.map …
```
=> Fix: Enable webpack example run alone

bin/styleguidist.js, docs/Configuration.md, loaders/__tests__/props-loader.spec.js, loaders/props-loader.js, loaders/styleguide-loader.js, loaders/utils/getProps.js, package-lock.json, package.json, scripts/__tests__/index.spec.js, scripts/__tests__/logger.spec.js, scripts/index.js, scripts/logger.js, scripts/make-webpack-config.js, scripts/schemas/config.js, scripts/utils/__tests__/sanitizeConfig.spec.js, scripts/utils/sanitizeConfig.js, test/run.server.js
=> Feat: Customizable logging, new logger option

examples/basic/src/components/Button/Readme.md, examples/cra/src/components/Button.md, examples/customised/src/components/Button/Readme.md, examples/preact/src/components/Button/Readme.md, examples/sections/docs/One.md, examples/sections/src/components/Button/Readme.md, examples/webpack/src/components/Button.md, loaders/utils/__tests__/chunkify.spec.js, loaders/utils/chunkify.js, src/rsg-components/Examples/Examples.js, src/rsg-components/Playground/Playground.js, src/rsg-components/Playground/Playground.spec.js, src/rsg-components/Playground/PlaygroundRenderer.js
https://github.com/styleguidist/react-styleguidist/issues/257
1) render preview for jsx, js, javascript by default
2) allow to pass settings for code viewer
```
```jsx // { "static": true, "wrapInIframe": true }
<span></span>
```
```
=> feat(*): allow to pass settings for markdown code viewer

docs/Cookbook.md, scripts/create-server.js
Currently, Vagrant with the VirtualBox provider does not work with styleguidist, as there are issues with webpack's default behavior. The way around this is to make webpack use a polling scheme for checking for changed files. This is currently not configurable in styleguidist.
This PR makes the `devServer.watchConfig` configurable so that it is possible to use styleguidist with Vagrant
Fixes #515
=> Feat: Allow devServer.watchConfig to be configured

bin/styleguidist.js
This PR changes "Style guide server started at:" notification to correctly state https protocol when starting RSG server with `{ devServer: { https: true } }`.
=> Output correct protocol when starting RSG server

src/rsg-components/Preview/Preview.js, src/rsg-components/Preview/Preview.spec.js
`Preview` doesn't unmount `Wrapper` it mounts when `Preview` is unmounted. As a result, clicking `IsolateButton`, all `Wrapper`s remain on the DOM including those irrelevant.
In this PR `Preview` is changed to clean up after itself.
=> Fix: Preview should unmount the Wrapper component when it unmounts

src/rsg-components/Props/PropsRenderer.js
We get an error if we have in the component propTypes something like this: 
```
items: PropTypes.oneOfType([
PropTypes.arrayOf(PropTypes.object),
PropTypes.arrayOf(PropTypes.array),
]).isRequired,
```
It happens because at the moment styleguidist use just type of prop (`arrayOf`), and when we have two or more same types in the `oneOfType`- type can't be used as key.
So this PR just adds an index as a suffix to key.
=> Fix duplicating of keys for 'arrayOf' prop type in the unions rendering

docs/Development.md
I found a small typo in the filename. `.spece.js` should be `.spec.js`.
=> Remove typo from testing section of the developer guide

examples/sections/styleguide.config.js, package-lock.json, package.json, src/rsg-components/Props/Props.spec.js, src/rsg-components/Props/PropsRenderer.js, src/rsg-components/Props/__snapshots__/Props.spec.js.snap
This PR improves the printing of objects in `defaultProps`, which had some issues in the existing version. See #524 for further details.
This PR removes the fallback of printing objects as strings. Instead, objects will be parsed, beautified, then finally displayed in a title. This mirrors the existing method used by `function` props.
Parsing is done with the [safe-eval](https://github.com/hacksparrow/safe-eval) library. Not sure if we actually need this library, though, as we are not in a node.js context here. Wanted to get some feedback first. We could use `eval` directly, or just render the unprettified source code representation in the title. Thoughts?
Fixes #524
=> Feat: Improve shape defaultProp rendering (#524)

src/rsg-components/Props/Props.spec.js, src/rsg-components/Props/PropsRenderer.js, src/rsg-components/Props/__snapshots__/Props.spec.js.snap
Hi,
I found another thing I found to be lacking with `defaultProps`. In the case where you specify a default value that is `null` or `undefined`, I would expect it to show that value. Instead, what you get is a title with that value, see below.
Here's a PR that makes an exception  for `null` and `undefined` values, and renders them as code instead.
=> Render null and undefined defaultValues as code

src/rsg-components/ReactComponent/ReactComponent.spec.js, src/rsg-components/ReactComponent/ReactComponentRenderer.js, src/rsg-components/ReactComponent/__snapshots__/ReactComponent.spec.js.snap
This is an implementation of one of the features from #195.
The Pathline component will not render if the path line is empty. I'm not sure if this requires an update to the docs.
Please let me know if anything needs changing.
=> Hide empty path line

loaders/__tests__/props-loader.spec.js, loaders/props-loader.js
Added support to re-compile component (invoking props-loader) when any of its dependencies gets changed. This will enable only when [`contextDependencies`](https://react-styleguidist.js.org/docs/configuration#contextdependencies) is configured.
Issued in favor of this [discussion](https://github.com/styleguidist/react-styleguidist/issues/551)
=> Added support to enable HMR for component dependencies

docs/Configuration.md, docs/Webpack.md, scripts/utils/__tests__/mergeWebpackConfig.spec.js, scripts/utils/mergeWebpackConfig.js
The `devtool` setting in your webpack config will now get passed through for non-production environments, e.g., running the hot-reloading server.
It will still get ignored for production builds.
Docs updated, and added a test.
=> Using devtools with react-stylegudist #456

docs/Configuration.md
As a best practice one should use absolute paths for Webpack stuff
=> Change require to show absolute path

package-lock.json, src/styles/setupjss.js
I added font-size to jss configuration, I couldn't find any tests for jss conf.
I test the Fix with my react components library and it works fine.
=> Fix: CSS EM unit is not isolate (#584)

loaders/props-loader.js
First of all, thanks for great project!
I started using `react-styleguidist` with Typescript and `react-typescript-docgen` and have found one really annoying bug. 
If there is no exported component in `.ts` file, `parse` from `react-typescript-docgen` return an empty array.
```ts
import * as React from 'react';
export interface MyComponentProps {
foo: string;
className?: string;
}
const MyComponent: React.SFC<MyComponentProps> = () => (...);
export default MyComponent;
```
It has to be ```export const MyComponent```, but during development you can forgot about this.
`props-loader.js` reaches line 45 and assumes that array is not empty. Then props[0], which is `undefined`, is passed to `getProps` function and `react-styleguidist` stops working. So, you have to add export to the component …
=> Omit component if propsParser returns an empty array

examples/sections/styleguide.config.js, src/rsg-components/Components/Components.js, src/rsg-components/Components/Components.spec.js, src/rsg-components/Components/__snapshots__/Components.spec.js.snap, src/rsg-components/ReactComponent/ReactComponent.js, src/rsg-components/ReactComponent/ReactComponent.spec.js, src/rsg-components/ReactComponent/__snapshots__/ReactComponent.spec.js.snap, src/rsg-components/Section/Section.js, src/rsg-components/Section/Section.spec.js, src/rsg-components/Section/SectionRenderer.js, src/rsg-components/Section/__snapshots__/Section.spec.js.snap, src/rsg-components/SectionHeading/SectionHeading.js, src/rsg-components/SectionHeading/SectionHeading.spec.js, src/rsg-components/SectionHeading/SectionHeadingRenderer.js, src/rsg-components/SectionHeading/__snapshots__/SectionHeading.spec.js.snap, src/rsg-components/Sections/Sections.js, src/rsg-components/Sections/Sections.spec.js, src/rsg-components/Sections/__snapshots__/Sections.spec.js.snap, src/rsg-components/StyleGuide/StyleGuide.js, src/rsg-components/StyleGuide/__snapshots__/StyleGuide.spec.js.snap
Added a `depth` prop to section heading and pass down through all sections.
Left in the `root` and `primary` props for now in case anyone is using them in a customised styleguide, but they should be deprecated and removed.
Also updated the sections example to demonstrate deeply nested sections.
=> Fix: Add depth to sections so heading levels are correct (#600)

Readme.md, docs/Webpack.md
my first pull request @sapegin :) 
added missing info when using Create React App together with TypeScript. Had to read webpack-config from react-scripts-ts/config/webpack.config.dev.js.
=> Docs: Added Create React App + Typescript info

src/index.js, src/rsg-components/slots/IsolateButton.js, src/rsg-components/slots/__snapshots__/IsolateButton.spec.js.snap
Current implementation ends up linking to the base url (`window.location.pathname`) which does not include the `#` sign so it will perform an HTTP request.
This PR changes the behavior - it will now navigate to `#/`
=> Fix navigating back from isolated / focus mode

src/rsg-components/Error/Error.spec.js, src/rsg-components/Error/ErrorRenderer.js, src/rsg-components/Error/__snapshots__/Error.spec.js.snap, src/rsg-components/Error/index.js, src/rsg-components/PlaygroundError/PlaygroundErrorRenderer.js, src/rsg-components/StyleGuide/StyleGuide.js, src/rsg-components/StyleGuide/StyleGuide.spec.js, src/rsg-components/StyleGuide/__snapshots__/StyleGuide.spec.js.snap
Adds `componentDidCatch()` to top-level `<StyleGuide />` component. We could arguably have added an additional `<ErrorBoundary />` layer in case there's an error in the `<StyleGuide />` component itself, but that seemed unlikely.
To test this, you would need to update to React 16 locally (I left that out of this PR because there's still some other pending tasks in #614 ) and then access a property on an undefined object or something in the render method of a component deep in the tree. Here's a screenshot of what it looks like:
Note that the console also logs the React-generated error, which is nice.
=> (feat): Adds componentDidCatch() to top-level component

examples/cra/package-lock.json, examples/cra/package.json
Related to #630. I updated `react-styleguidist`, and regenerated `package-lock.json`. `cd`ing into the example's directory and running `npm run styleguide` now works as expected. I can look into why `npm run start:cra` doesn't work from the root dir next!
=> Update react-styleguidist in CRA example

Readme.md
Adds credits for logo designers to readme. Similar to https://github.com/styleguidist/snapguidist
=> docs: Add credits for logo designers

src/rsg-components/Preview/Preview.js, test/jestsetup.js
=> clear console on reload

docs/Documenting.md
In issue #641 I was confused that code blocks without language tags were
being rendered as a React component, and not a code documentation block.
It turned out this was for backward compatibility reasons. This commit
updates the documentation to hopefully avoid such confusion in the
future. The docs now also suggest a workaround.
=> Explain behavior for code blocks w/o language tag

src/rsg-components/Error/ErrorRenderer.js, src/rsg-components/PlaygroundError/PlaygroundErrorRenderer.js, src/styles/theme.js
Removes red background and hacks with negative margins that were required for it to work.
Closes #576, #667
=> Fix: Correct whitespace around error messages with noeditor modifier

docs/Cookbook.md, scripts/make-webpack-config.js, src/rsg-components/ReactComponent/ReactComponent.js
This fixes https://github.com/styleguidist/react-styleguidist/issues/677
- Add a new environment variable called `STYLEGUIDIST_ENV` to check if we're in dev server or static build mode
- Allow the user to pass `NODE_ENV` to Webpack's config, to determine if React will use its production or development build
=> Fix node env

scripts/create-server.js
Address bug #682 by setting the webpack [`watchContentBase`](https://webpack.js.org/configuration/dev-server/#devserver-watchcontentbase) flag to `true` when an `assetDir` is provided.
=> Reload dev server when assets change

package-lock.json, package.json
Fix #686 by upgrading react-docgen to [3.0.0-beta9](https://github.com/reactjs/react-docgen/releases/tag/v3.0.0-beta9) which includes changes from [2.20.0](https://github.com/reactjs/react-docgen/releases/tag/v2.20.0) as well.
=> Upgrade react-docgen to 3.0.0-beta9

scripts/create-server.js
There is currently no way to override webpack dev server options. For example, we specifically want the dev server to look at `node_modules/` too (to develop using linked dependencies) and there isn't a way to do that.
=> Allow overriding default webpack dev server options

src/rsg-components/Playground/PlaygroundRenderer.js
According to https://react-styleguidist.js.org/docs/cookbook.html#how-to-change-styles-of-a-style-guide you are able to find component style names using React Developer tools. Unfortunately, last tab uses `classes.tab`, but it's not set in styles, so react renders with class `rsg-undefined`.
=> Add 'tab' key to Playground component's style

docs/Cookbook.md
This PR was motivated by this comment: https://github.com/styleguidist/react-styleguidist/issues/737#issuecomment-352661552
I couldn't easily find where to build and run the site to test this, but it should just be a straightforward addition to the docs.
=> template example added

package.json
`prepare` will run:
- before publish (for npm4+)
- after install (for npm4+)
- after styleguidist gets installed as dependency from github (for npm5+)
=> Use prepare script to allow npm@5+ compiling git dependency

docs/Thirdparties.md
This PR adds some documentation for using Styled Components `ThemeProvider` in the Third Parties section. I figured this out last night, but I thought it might be helpful for people getting started to have some explicit documentation.
If you'd like the copy changed at all, let me know. Happy to update it.
=> Docs: Adds documentation for Styled Components ThemeProvider

docs/Cookbook.md
Added a cookbook example to demonstrate dynamically loading components using require.context.
=> Add example using require.context (fixes #808)

docs/Configuration.md
The current link is in camelCase which means that the link to `editorConfig` on this page https://react-styleguidist.js.org/docs/configuration.html doesn't work.  This PR normalises the case to `editorconfig`, allowing the [link](https://react-styleguidist.js.org/docs/configuration.html#editorconfig) to work.
=> Fix broken fragment link to editorConfig settings

src/rsg-components/Code/Code.spec.js, src/rsg-components/Code/CodeRenderer.js, src/rsg-components/Code/__snapshots__/Code.spec.js.snap, src/rsg-components/Markdown/Markdown.js, src/rsg-components/Markdown/Pre/Pre.spec.js, src/rsg-components/Markdown/Pre/PreRenderer.js, src/rsg-components/Markdown/Pre/__snapshots__/Pre.spec.js.snap, src/rsg-components/Markdown/Pre/index.js, src/rsg-components/Markdown/__snapshots__/Markdown.spec.js.snap, src/rsg-components/Name/NameRenderer.js, src/rsg-components/Name/__snapshots__/Name.spec.js.snap, src/rsg-components/Type/Type.spec.js, src/rsg-components/Type/TypeRenderer.js, src/rsg-components/Type/__snapshots__/Type.spec.js.snap
... to allow easier overriding by consumers of Markdown components.
* Support both escaped and non-escaped code blocks
* Introduce Markdown > Pre component also for preformatted code
=> Refactor: combine existing Code component with the Markdown Code component. #613

loaders/styleguide-loader.js, scripts/__tests__/__snapshots__/make-webpack-config.spec.js.snap, scripts/__tests__/make-webpack-config.spec.js, scripts/make-webpack-config.js
This fixes #788 by firstly testing for `editorConfig.theme` in the config and using that if present.  This falls back to using `highlightTheme` (deprecated) so backwards compatibility is assured.
=> Use editorConfig.theme for CodeMirror theme

cypress/integration/component_spec.js, cypress/integration/core_spec.js, cypress/integration/initial_spec.js
Hey,
wrote up some integration tests with cypress (#776).
They feel a bit fragile, I don't like hooking up to css classes or text contents for testing, but I can't come up with better ways yet.
Had some pain with code editor, since the codemirror is using an empty hidden textarea behind the scenes to track keystrokes and update the divs with representation, so the test for this is a bit hacky.
=> add cypress tests for core and single component

docs/Configuration.md
This PR fixes a link which is returning a `404`.
=> Fix broken link on the docs

package-lock.json, package.json, src/rsg-components/Markdown/Markdown.js, src/rsg-components/Markdown/Markdown.spec.js, src/rsg-components/Markdown/Table/Table.spec.js, src/rsg-components/Markdown/Table/TableBodyRenderer.js, src/rsg-components/Markdown/Table/TableCellRenderer.js, src/rsg-components/Markdown/Table/TableHeadRenderer.js, src/rsg-components/Markdown/Table/TableRenderer.js, src/rsg-components/Markdown/Table/TableRowRenderer.js, src/rsg-components/Markdown/Table/__snapshots__/Table.spec.js.snap, src/rsg-components/Markdown/Table/index.js, src/rsg-components/Markdown/__snapshots__/Markdown.spec.js.snap
This makes it easier for consumers to override individual components in their styleguide, specifically tables in this PR.
* Update markdown-to-jsx to v6.4.1 to get some table rendering bug fixes. [Release notes](https://github.com/probablyup/markdown-to-jsx/releases/tag/6.3.2)
=> refactor: introduce Table components for use in Markdown #613

docs/Cookbook.md
I noticed that the link was broken on the page due to an extra "e" in both the text and link. I also added a question mark onto the end of the text to match the rest of the formatting on the page.
=> fix docs: typo in cookbook link to storybook difference

docs/Components.md, docs/Configuration.md, loaders/utils/__tests__/getComponentFiles.spec.js, loaders/utils/getComponentFiles.js
This PR addresses the following issue: #774 
Now along with a string or function it is possible to pass an array of file paths to `components` property of the config.
=> feat: allow use of array of component paths in the config file

docs/Components.md, docs/Thirdparties.md, src/utils/__mocks__/getComponent.js, src/utils/__tests__/getComponent.spec.js, src/utils/__tests__/globalizeComponent.spec.js, src/utils/getComponent.js, src/utils/globalizeComponent.js
This responds to the need expressed in #820 and #633 
It preserves the base case of Styleguidist loading `default` exports by default, while adding some limited support for exposing named exports where a module exposes no default export and either:
- just one named export; or
- a named export which matches the component name understood by Styleguidist.
I think these cases are non-controversial. In each case, it is almost guaranteed that the developer intends these named exports to be interpreted as the exported component.
I have added documentation covering this. The documentation is careful to emphasise that this is not a complete solution for named exports - Styleguidist will do its best but in complicated cases will just fall back to exposing the module as a whole, as it currently …
=> Add limited support for named exports. Add docs relating to this support.

scripts/templates/index.html, src/index.js
This PR addresses issue #753 with the following changes:
* use 'rsg-root' id insted of 'app' on the main container
* print deprecation warning to the console if 'app' id is used in custom template
=> feat: change template container id to prevent clashes

src/rsg-components/Preview/Preview.js, src/rsg-components/Preview/Preview.spec.js, src/rsg-components/Preview/__snapshots__/Preview.spec.js.snap
=> fix: change state assigment

src/utils/__tests__/getInfoFromHash.spec.js, src/utils/getInfoFromHash.js
Fix the bug when section name is not english such as chinese, then switch router will be failed.
repeat step:
1. set option `pagePerSection: true`
2. change some section name to chinese like `测试`
3. click the link to the section
4. click other section link
5. click the chinese section again
=> Fix the bug when section name is not english

loaders/utils/__tests__/__snapshots__/getSections.spec.js.snap, loaders/utils/processComponent.js, package-lock.json, package.json, scripts/__tests__/__snapshots__/make-webpack-config.spec.js.snap, scripts/make-webpack-config.js
=> Chore: update to webpack 4

.babelrc, package.json, src/rsg-components/Editor/EditorLoader.js
Fixes #900
I've read [Webpack's documentation](https://webpack.js.org/guides/code-splitting/#dynamic-imports) which links to [Babel's documentation](https://babeljs.io/docs/plugins/syntax-dynamic-import/#installation) and this seems the way to go.
I've never used dynamic imports before, so feedback is appreciated.
=> Replace System.import with import

docs/Configuration.md, docs/GettingStarted.md, docs/Thirdparties.md, examples/basic/Readme.md, examples/cra/Readme.md, examples/customised/Readme.md, examples/express/Readme.md, examples/preact/Readme.md, examples/react-native/README.md, examples/sections/Readme.md, examples/webpack/Readme.md
This PR updates the documentation to use `npx` instead of custom npm scripts.
Closes #836
=> Docs: Use `npx` instead of custom scripts

src/utils/splitExampleCode.js
Closes #899 
I replaced the `lib/utils/splitExampleCode.js` file in my affected repo with the code built from this change. Everything seems to be working just fine.
=> Fix: find() compatibility with IE11

bin/styleguidist.js
When explicitly setting the serverHost to 127.0.0.1 or localhost,
urls.lanUrlForTerminal is undefined. It makes no sense to print out
undefined, therefore only show the 'On your network' line when it's
defined.
=> bin: Don't report 'On your network' on localhost

src/rsg-components/Markdown/Markdown.js
If you want to have custom react components that are rendered via markdown it requires reimplementing the  Markdown class.   By exporting the overrides someone could add there own component 
Example:
```
import {baseOverrides} from 'react-styleguidist/src/Markdown/Markdown'
import MySpecialComponent from 'my-special-component';
baseOverrides.MySpecial = { component:MySpecialComponent }
```
Then later in the a markdown file.
```markdown
I would really like a custom react component
<MySpecial/>
Boom! its there.
```
=> Export overrides to support easier subclassing and configuration

src/rsg-components/Editor/Editor.js, src/rsg-components/Editor/Editor.spec.js, src/rsg-components/Editor/__snapshots__/Editor.spec.js.snap
Fixes #973.
Added new `editorConfig` prop to `Editor` which overrides context so that `Editor` can be used by future plugins.
=> Add editorConfig to Editor

src/rsg-components/Playground/Playground.js, src/rsg-components/Playground/__snapshots__/Playground.spec.js.snap
Fixes #977
`Playground` passes `evalInContext` to `Slot`
=> Playground passes evalInContext to Slot

package-lock.json, package.json
The issue of #922 has been resolved with `markdown-to-jsx@6.6.3` (thanks probablyup), therefore it would make sense to update the dependency.
=> Update `markdown-to-jsx` dependency

docs/Configuration.md, scripts/schemas/config.js
=> Feat: Allow usage of NODE_PORT for switching the serverPort

src/utils/splitExampleCode.js
I ran into an issue trying to run `async`/`await` code in an example. I'm only targeting new Chrome and FF for the styleguide so i've mostly disabled the buble transforms. The problem tho is that this file here, also tries to parse the code, which fails silently.
I think this should be a safe change, and backwards compatible
=> Use latest ecmaVersion parsable by acorn

docs/Configuration.md
Example code from `updateDocs` option is broken because of missing `file` argument
=> Fixed missed argument in updateDocs config method

package-lock.json, package.json
The `^` or `~` semver operators don't work as expected here, because `'beta12'` ends up being compared as a string, and `'beta9' > 'beta12'`.
This issue has also been reported upstream as reactjs/react-docgen#275.
=> Fix react-docgen version to exactly 3.0.0-beta12

bin/styleguidist.js, docs/CLI.md
Fixes https://github.com/styleguidist/react-styleguidist/issues/918
I had a look at #748 which uses `opn` directly, but I decided to go another path.
I've used `react-dev-utils`  [openBrowser](https://github.com/facebook/create-react-app/blob/next/packages/react-dev-utils/openBrowser.js), this used by `react-scripts` [here](https://github.com/facebook/create-react-app/blob/next/packages/react-scripts/scripts/start.js) to open the browser, it has some cool things like reusing an existing tab, but it also does some things based on the `BROWSER` env variable, so I have mixed feelings about using it and I'd love to hear what you think.
Since I needed the `urls` to open the browser I changed the `printServerInstructions` function to receive the `urls` as an argument, it should be fine since …
=> Add --open argument to open default browser on start

docs/Configuration.md, docs/Cookbook.md, examples/basic/styleguide.config.js, loaders/styleguide-loader.js, scripts/schemas/config.js, src/rsg-components/StyleGuide/StyleGuide.js, src/rsg-components/StyleGuide/StyleGuide.spec.js, src/rsg-components/StyleGuide/StyleGuideRenderer.js, src/rsg-components/StyleGuide/__snapshots__/StyleGuide.spec.js.snap, src/rsg-components/Version/Version.spec.js, src/rsg-components/Version/VersionRenderer.js, src/rsg-components/Version/__snapshots__/Version.spec.js.snap, src/rsg-components/Version/index.js
When documenting libraries (of components or otherwise), I at least find it useful to see which version of said library the documentation pertains to. This PR adds a "version" string field to the config that's passed on to the renderer and if not empty, is included in the sidebar just under the title, with some discreet styling that fits the base theme.
I've also added the version to the basic example, where it's read from the example's `package.json` file.
=> Feat: Add a user-configurable optional "version" indicator to the sidebar

docs/Configuration.md, loaders/styleguide-loader.js, scripts/__tests__/config.spec.js, scripts/__tests__/make-webpack-config.spec.js, scripts/make-webpack-config.js, scripts/schemas/config.js, src/index.js
By default RSG binds to a div with an id of `rsg-root` with no way of overriding this. We needed to import multiple RSG bundle files into our work documentation site and as such needed to be able to specify the id of the element we wanted the bundles to bind to.
In your `styleguide.config.js` you can now specify an optional `mountPointId` to specify the id of the DOM element you want the app to bind to. It will default to the existing `rsg-root` if not specified.
I have tried to add some tests but might need some guidance here to make sure I am on the right track.
=> Feat: Made the mounting point id configurable.

src/utils/getRouteData.js
If isolated is `true`, so it shoud try to search with recursivity until find the component.
=> Fix: Appear page not found when a component is isolated

docs/Documenting.md
This fixes a typo and a missing space character in the documentation.
=> Fix Typo: Best Button

docs/Configuration.md
I checked the source but I don't think this config reads in any env variables?
=> Remove error default value for serverPort

src/rsg-components/Pathline/PathlineRenderer.js
- the "Pathline" breaks the responsive view if it gets too long as there will be a horizontal scrollbar/or the whole document will be scaled down (depending on the browser)
=> fix: allows pathline to wrap

loaders/examples-loader.js, loaders/utils/__tests__/__snapshots__/chunkify.spec.js.snap, loaders/utils/__tests__/chunkify.spec.js, loaders/utils/chunkify.js
I am in the process of trying to simplify vue-styleguidist and I need to extract every react specific detail of styleguidist.
In this spirit, we want to be able to use example-loader.
Bad luck, we allow the use of "vue" as a language for our examples. 
This brought https://github.com/vue-styleguidist/vue-styleguidist#200
I thought the best way to clean up vsg's code while making rsg a little more powerful was to add an option to the example-loader customLangs.
Wether it's additional langs or replace entirely can be changed.
Thank you for your remarks.
Bart
=> Allow chunkify to accept other extensions than js, jsx and html

docs/Configuration.md, docs/Documenting.md, examples/basic/src/components/Button/Readme.md, examples/basic/styleguide.config.js, src/scripts/__tests__/__snapshots__/make-webpack-config.spec.js.snap, src/scripts/__tests__/make-webpack-config.spec.js, src/scripts/make-webpack-config.js, src/scripts/schemas/config.js, test/run.server.js
Closes #1076
Add new config option `moduleAliases` to define aliases for modules, that you can import in your examples, to make example code more realistic and copypastable:
```javascript
const path = require('path')
module.exports = {
moduleAliases: {
'rsg-example': path.resolve(__dirname, 'src')
}
}
```
````jsx static
// ```jsx inside Markdown
import React from 'react'
import Button from 'rsg-example/components/Button'
import Placeholder from 'rsg-example/components/Placeholder'
````
Check out the [webpack resolve.alias documentation](https://webpack.js.org/configuration/resolve/#resolve-alias) for available syntax.
=> Import aliases

src/rsg-components/Pathline/PathlineRenderer.js, src/rsg-components/Usage/Usage.js, src/rsg-components/slots/UsageTabButton.js
In support of #1155, this PR improves the check for whether props and methods exist in Usage and UsageTabButton components.
=> Improve check for props and methods rendering

src/client/rsg-components/Markdown/Markdown.spec.js, src/client/rsg-components/Markdown/MarkdownHeading/MarkdownHeading.spec.js, src/client/rsg-components/Markdown/MarkdownHeading/MarkdownHeadingRenderer.js, src/client/rsg-components/Markdown/MarkdownHeading/__snapshots__/MarkdownHeading.spec.js.snap, src/client/rsg-components/Markdown/__snapshots__/Markdown.spec.js.snap
This PR introduces preliminary support for linking to headings
within an example text using markdown headings.
Since linking in this way requires using the # character it means you
can't link to a section in isolated mode (for instance to
http://localhost:6060/#!/WrappedButton#example-section) on account of
the #! being reserved for routing.
It may still be useful to the reporter of #833 for linking to a section in the list
view, and may act as a base for further improvements 🙂
=> Feat: Add generated id to markdown headings (#833)

src/rsg-components/Preview/Preview.js
Preview uses a relative path to grab `ReactExample` which is causing issues when trying to use an aliased version of it.
=> Use rsg-components import path in Preview to allow for custom ReactExample

src/rsg-components/ComponentsList/ComponentsListRenderer.js
https://github.com/styleguidist/react-styleguidist/issues/1186
Implemented check on `ComponentsListRenderer` for the current `window.location.hash` in order to verify which one of the items is currently selected. Added a  `background-color` change to the selected item, and also added some padding to the item to make the highlight selection better due to the previous lack of padding.
=> Highlight currently selected page on sidebar

.travis.yml
I noticed that every pull request was trying to run the release and documentation stages.
I thought it was a waste of time.
This filters the stages in PR builds.
=> Fix(ci): Only run release and documentation on master branch

examples/basic/package-lock.json, examples/basic/package.json
This fixes #1232 (instead of just closing and locking it). The main thing that fixes the install is deleting package-lock.json and regenerating it. I tried investigating further why that helped and it seems to becease two different acorn versions are installed and the main one should be 6.0.4, not 5.7.1. Otherwise you get this weird import error.
=> Fix basic example to make install instructions work

src/client/rsg-components/ComponentsList/ComponentsListRenderer.js
* Usage of the hasInHash function to determine the current section to highlight on the sidebar causes partial matches to be highlighted as well. This is because the hasInHash function uses indexof.
* Removed usage of hasInHash and its import in the ComponentsListRenderer.
* Compare string in order to determine the right section to highlight. similar to before I compare the windowHash with the current item href.
=> fix: Incorrect current section highlighting on partial match closes #1237 

docs/Webpack.md
Following the docs I was trying to load a 3rd party css library by requiring it:
`require: [path.resolve(__dirname, "node_modules/react-dates/lib/css/_datepicker.css")],`
and adding the corresponding loader as it is shown [here](https://react-styleguidist.js.org/docs/webpack.html#custom-webpack-config) but didn't work out.
```js
{
test: /\.css$/,
loader: 'style-loader!css-loader?modules'
}
```
Changing `loader` for `use` did the trick.
```js
{
test: /\.css$/,
use: ['style-loader', 'css-loader'] 
}
```
=> Docs: Fix webpack css loader example

src/scripts/utils/__tests__/findUserWebpackConfig.spec.js, src/scripts/utils/findUserWebpackConfig.js
Since react-scripts 2.1.1, the config file is named webpack.config.js instead of webpack.config.dev.js.
=> Fix webpack config file name for react-scripts > 2.1.1

docs/Configuration.md, docs/Development.md
I've done a search for all links to code in GitHub from the docs and found these 3 broken links :)
=> Fix a few links to repo code in docs

src/loaders/utils/getComponentFiles.js
Addresses hot reloading issue for windows
=> Fix: Resolve path of component files (#1246)

src/client/utils/__tests__/transpileImports.spec.js, src/client/utils/rewriteImports.js
=> Allow trailing comma in named imports in examples

src/client/styles/prismTheme.js, src/client/styles/theme.js
- Add `theme.color.codeBase` property to config
- Allow syntax highlight default color to set without affecting base color
- The `codeBase` and `codeBackground` can be set to allow finer control of code text contrast ratios. e.g. Create dark themes for code samples.
The `them.color.code*` properties can be used to customized the syntax highlight theme. However, setting a dark color as the codeBackground makes the code almost unreadable (due to low contrast ratios). 
Static Code Block
Editable Code Block
Static Code Block
Editable Code Block
Yes. 
- Using custom style wrappers for `rsg-components/Editor` and `rsg-components/Markdown/Pre` components 
There could be other approaches, but it seems most approaches require much more code change than should be required to customize colors with …
=> Feat: Allow code base color to be customized with theme config

examples/styled-components/babel.config.js, examples/styled-components/package-lock.json, examples/styled-components/package.json, examples/styled-components/src/StyleGuideWrapper.tsx, examples/styled-components/src/ThemeProvider.tsx, examples/styled-components/src/components/Button/Button.md, examples/styled-components/src/components/Button/Button.tsx, examples/styled-components/src/components/Button/index.ts, examples/styled-components/src/styles.ts, examples/styled-components/src/theme.ts, examples/styled-components/styleguide.config.js, examples/styled-components/tsconfig.json
Adding a simple example with styled-components and TypeScript
=> Add styled-components with typescript example

package-lock.json, package.json, src/client/rsg-components/Markdown/Markdown.js, src/client/rsg-components/Markdown/Markdown.spec.js
* Add tests for single-line, multi-line comments
* Hide HTML comments in Markdown files
Updated this PR, added a fix for hiding HTML comments in Markdown files
~Refers~ Closes #1326
=> Fix: Hide HTML comments in Markdown files

package-lock.json, package.json, src/loaders/utils/__tests__/getExamples.spec.js, src/loaders/utils/getExamples.js
If a file does not exist in fs we have errors during the build.
In this case, we should continue to use the default example file.
iss: #1338
=> Fix getExampleFilename customization if file is not exist

src/loaders/utils/__tests__/__snapshots__/getSections.spec.js.snap, src/loaders/utils/getSections.js
Add `section` prefix to all auto generated headings
So links to components and sections will be
`section-introduction`, `section-color` etc.
iss: #1342
=> Fix headers conflict with navigation link IDs

src/scripts/__tests__/make-webpack-config.spec.js, src/scripts/make-webpack-config.js
copy-webpack-plugin is not allowing `from` to be as an array.
If we still want to use `from` and support array format for
assetsDir, then we should pass an array of objects {from: ...} to
copy-webpack-plugin
iss: #1320
=> Fix build if assetsDir is an array

docs/Configuration.md, src/client/utils/__tests__/compileCode.spec.js, src/scripts/schemas/config.js
iss: #1371
Add `transforms: { asyncAwait: false }` for default compilerConfig to make async/await work by default
Update default value of compilerConfig in the configuration documentation.
We have the error here because styleguidinst has updated version of [bublé](https://github.com/bublejs/buble) ([from v0.9.4 to v0.9.7](https://github.com/mendrew/react-styleguidist/commit/48f72208d6cfb19e34654f22b47c86d8531e2b71#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R34)) which does actual code transformation.
In latest version of bublé they throw this error because right now [bublé cannot transpile async](https://github.com/bublejs/buble/issues/109#issuecomment-380854164), so they've added a special transform option called `asyncAwait` to pass `async` through as before. Here the code, how they do it: …
=> Disable asyncAwait transform to make async/await work by default

src/client/utils/__tests__/getUrl.spec.js, src/client/utils/__tests__/handleHash.spec.js, src/client/utils/getUrl.js, src/client/utils/handleHash.js
If you have a forward slash in your section name, the pagePerSection links are all broken,
resulting in "Page not found".
For example:
pagePerSection links break when section name includes a "/", like `name: '@foo/components'`
The solution is just to encode a name in the getUrl and then correctly
decode it in the router hash logic.
iss: https://github.com/styleguidist/react-styleguidist/issues/1332
=> Fix section pages if section name has inappropriate symbols

src/client/utils/__tests__/getUrl.spec.js, src/client/utils/getUrl.js
Follow up of https://github.com/styleguidist/react-styleguidist/issues/1332
This appears https://github.com/styleguidist/react-styleguidist/pull/1384 has fixed the top level section link,
but any sub-links within that section are still unencoded and result
in "Page not found".
=> Encode sublinks in url to fix broken routes

src/loaders/utils/__tests__/getNameFromFilePath.spec.js, src/loaders/utils/getNameFromFilePath.js
iss: https://github.com/styleguidist/react-styleguidist/issues/1381
It is happening in a case when `react-docgen` (any propsParser) is failed
and we are trying to guess displayName based on the file path.
We capitalized every case in the string instead of just words separated
by `-` or started with a small letter.
So, by mistake `ButtonTS` in file name becomes `ButtonTs` display name for
component when we expect `ButtonTS`
=> Fix component name capitalization issue

docs/Webpack.md
as discussed in https://github.com/styleguidist/react-docgen-typescript/issues/71#issuecomment-362370750, some compiler options break component discovery.  the safest strategy is to always include the tsconfig from user space, which improves component detection.
add `.withCustomConfig` call, as it's quite commonplace to for consumers to tweak their compiler settings
=> docs(webpack): improve typescript usage

docs/Webpack.md
add clarification when adding webpack configs to a non-webpack project to clearly indicate what should be added to styleguide.config.js or to webpack.config.js
=> Docs: Add clarification to non-webpack project docs

src/scripts/make-webpack-config.js
#1189 
PR to fix a bug with inline JavaScript comments in template script tags. The comments were causing the rest of the script to be commented out when whitespace got removed.
My fix follows an example from [mini-html-webpack-plugin](https://github.com/styleguidist/mini-html-webpack-plugin) that uses [html-minifier](https://github.com/kangax/html-minifier). I'm using this to set options on how the HTML is minified.
I see two possible issues with what I have so far.
1. Needing to add **html-minifier** to package.json.
2. Whether or not I should set the **minifyJS** option to true. It produces cleaner minified HTML but removes comments from the JavaScript within script tags.
Here's an example where I minify the JS.
And here's an example where I don't.
=> [WIP] Template inline js comments

docs/Webpack.md, package-lock.json, package.json, src/client/rsg-components/Pathline/PathlineRenderer.js, src/client/rsg-components/slots/IsolateButton.js
Fixes #1318 
Updated **package.json** and the two files where react-icons is used so that they have the correct paths for the new version.
I can't figure out why **Webpack.md** keeps getting formatted differently when I commit. My **.eslintrc** looks to be the same as the one on master.
=> Upgrade react-icons to 3.7.0

src/client/rsg-components/TableOfContents/TableOfContents.js
If a section contains only one subsection,
styleguidist will try to optimize.
It will make the section disapear and show
its components instead.
If this section only contain sections, no components,
it should optimize to sections and not to components.
CF: https://github.com/vue-styleguidist/vue-styleguidist/issues/492
=> Fix: Single sections OK to contain no component

src/client/rsg-components/TableOfContents/TableOfContents.js, src/client/rsg-components/TableOfContents/TableOfContents.spec.js
On the last commit, I did not take into account that the sections array could be empty and not null.
When there was components only and no sections we had the behavior described in the issue attached below.
This is the fix needed.
Sorry again
closes https://github.com/vue-styleguidist/vue-styleguidist/issues/561
=> Fix: If components only styleguide, build TOC

package-lock.json, package.json
[Snyk](https://snyk.io/) has reported a security vulnerability through the following dependency chains:
1. `react-styleguidist@9.1.3 › react-dev-utils@6.1.1 › sockjs-client@1.1.5 › eventsource@0.1.6 › original@1.0.0 › url-parse@1.0.5`
1. `react-styleguidist@9.1.3 › react-dev-utils@6.1.1 › sockjs-client@1.1.5 › url-parse@1.2.0`
Details of the Snyk report:
> **Overview**
> url-parse is a Small footprint URL parser that works seamlessly across Node.js and browser environments.
>
> Affected versions of this package are vulnerable to Open Redirect, Server Side Request Forgery (SSRF) and Bypass Authentication Protocol due to returning wrong hostname.
> **Remediation**
> Upgrade url-parse to version 1.4.3 or higher.
Details of dependency updates:
- `react-dev-utils@9.0.3` updates …
=> Update react-dev-utils to ^9.0.3

docs/Configuration.md, src/scripts/make-webpack-config.js, src/scripts/schemas/config.js
Sometimes `terser` can cause errors or be unwanted for debugging purpose.
I just had all my documentations broken and this will help me behave quickly when minify step is unwanted. 
Related to https://github.com/terser/terser/issues/490
=> Feat: minimize options to be able to disable the js compression

docs/Configuration.md, docs/Cookbook.md, docs/Development.md, docs/Documenting.md, docs/Maintenance.md, docs/Thirdparties.md, docs/Webpack.md
I went through and fixed a handful of typos/grammar issues in the docs. Some of the changes are pretty obvious typos/grammar problems. Others are a bit more debatable, so let me know if you disagree with any of the changes.
Also, it looks like Maintenance.md uses "change log" instead of "changelog" throughout the doc. From what I've seen online, "changelog" is the preferred term so let me know if I'm okay to go through and change it there.
=> Docs: Fixed typos/grammar mistakes in the docs

examples/sections/src/components/MyLabel/Label.js, examples/sections/src/components/MyLabel/Readme.md, examples/sections/src/components/MyLabel/index.js, examples/sections/styleguide.config.js, src/client/utils/__tests__/getUrl.spec.js, src/client/utils/getUrl.js
This PR is a suggested fix for https://github.com/styleguidist/react-styleguidist/issues/1454
The issue is that if you have more than one component with the same name, the isolated mode will incorrectly show all of the components of the same name (instead of just the one you clicked on).
This fix solves the issue by prepending the existing hash path from the page the user came from. By prepending this hash path, Styleguidist correctly scopes the isolated example to just the desired component. 
You can test this by doing `npm run start:sections` on my branch and trying to click into the isolated mode for either of the duplicate `Label` components.
Fix demo:
Open questions:
- I'm not familiar with the `noChrome` feature, I _think_ this is the correct behavior there too but I'm not 100% …
=> Fix duplicate isolated components

docs/Configuration.md, docs/Cookbook.md
I update some obsolete links in theming docs. I found it when I was trying to theme my style guide.
=> Docs: update theme links

src/client/rsg-components/Styled/index.ts
When running the standard basic example, one gets a warning in webpack:
```sh
WARN  Compiled with warnings
./lib/client/rsg-components/Styled/index.js
Attempted import error: 'JssInjectedProps' is not exported from 'rsg-components/Styled/Styled'.
@ ./lib/client/rsg-components/StyleGuide/StyleGuideRenderer.js
@ ./lib/client/rsg-components/StyleGuide/StyleGuide.js
@ ./lib/client/rsg-components/StyleGuide/index.js
@ ./lib/client/utils/renderStyleguide.js
@ ./lib/client/index.js
@ multi ./lib/client/index ./node_modules/react-dev-utils/webpackHotDevClient.js
```
babel does not understand the difference between exposing an interface and an actual js object.
Hence the warning. 
This change fixes it.
=> Fix: remove style warning when compiling

src/client/rsg-components/Markdown/Pre/PreRenderer.tsx
iss: https://github.com/styleguidist/react-styleguidist/issues/1450
Add `overflow: auto` to the `pre` tags
Example:
=> Fix overflow in code examples with long strings

package-lock.json, package.json
This `acorn` update to `6.4.0` version should fix issues like:
- https://github.com/styleguidist/react-styleguidist/issues/1321;
- https://github.com/styleguidist/react-styleguidist/issues/1312;
- https://github.com/styleguidist/react-styleguidist/issues/1278;
- https://github.com/styleguidist/react-styleguidist/issues/1310.
More about `acorn@6.4.0` — https://github.com/acornjs/acorn/releases/tag/6.4.0.
=> Fix: Update acorn to 6.4.0 to fix several issues

src/loaders/__tests__/examples-loader.spec.ts, src/loaders/examples-loader.ts
When you have a component like 
```tsx
import React from 'react';
import styled from 'styled-components';
export const C: React.FC = () => {
...
}
const StyledC = styled(C)``;
export default StyledC;
```
so that you can use non-styled (name-exported) components for testing, styleguidist picks up the named export instead of the default export and breaks the styling in examples. 
If I understand [this part of the doc](https://react-styleguidist.js.org/docs/components.html#default-vs-named-exports) correctly, isn't this supposed to be the case? As in it will try to find
1. default exports 
2. if not found => single named export
3. if not found => named export with the same name
I'm aware there are a few workarounds to get my example above working, but just in case the current behavior isn't …
=> Honor default exports over named exports

src/client/rsg-components/Props/renderDefault.tsx
Styleguidist crashes when default prop isn't a string, e.g. a number.
=> Fix crashes when DefaultProp isn't a string

src/client/utils/__tests__/getUrl.spec.ts, src/client/utils/getUrl.ts
issue link: https://github.com/styleguidist/react-styleguidist/issues/1492
This issue occurred because of the fix that have been made in version 10.0.1 for the issue: https://github.com/styleguidist/react-styleguidist/issues/1454
Hashed Url example: the "#button" in the url is an example of Hashed Url...it gets appended after clicking the Button component in the side-Navbar...
After the issue #1454 was resolved...it was taking the hashed url token in the isolated page(which opens after clicking the fullscreen icon) url as you can see below
after clicking the fullscreen icon we got results like this!
so this was the issue which is resolved by doing a simple check i.e. we are verifying if the currentHash that we are getting in the 'buildIsolatedOrNoChromeFragment()' function is a …
=> fix:(isolation mode issue) issue #1492

package.json
When running `npm run compile` all spec.ts and tsx files are compiled into the lib folder which result in publishing tests to npm.
I remove this compilation, to make the command faster and avoid conflicts with other libraries.
=> Build: Avoid compiling spec files when publishing

examples/basic/package-lock.json, examples/basic/package.json, examples/customised/babel.config.js, examples/customised/package-lock.json, examples/customised/package.json, examples/express/babel.config.js, examples/express/package-lock.json, examples/express/package.json, examples/preact/babel.config.js, examples/preact/package-lock.json, examples/preact/package.json, examples/react-native/package-lock.json, examples/react-native/package.json, examples/sections/package-lock.json, examples/sections/package.json
I encountered the following error running the **customized** example.
Upgrading the packages in package.json fixed that problem. Updating the babel config fixed a problem that the package upgrade introduced with core-js.
=> Fix: Running the customized example results in an error

docs/Cookbook.md, package.json
As previously mentioned, I want to be able to use the types generated by rsg in vue-styleguidist.
This publishes the types with the compiled library.
There is a known limitation: `rsg-component` aliased path have to be kept in the `tsconfig.json` of any project using the types. It should redirect to `node_modules/react-styleguidist/lib/client/rsg-component`.
=> Build: Publish typings on travis publish

package.json
the npm run compile fails on windows 10. 
The single quote are not something that the cmd terminal accepts easily.
Since the single quotes are not necessary on linux or macos, we could get rid of them.
=> Build: Make sure compile works on windows

docs/Thirdparties.md
documentation update for #1508
=> doc update for typescript props config

src/client/rsg-components/ComponentsList/ComponentsList.spec.tsx, src/client/rsg-components/ComponentsList/ComponentsListRenderer.tsx, src/client/rsg-components/TableOfContents/TableOfContents.spec.tsx, src/client/rsg-components/TableOfContents/TableOfContents.tsx, src/client/rsg-components/TableOfContents/__snapshots__/TableOfContents.spec.tsx.snap, src/typings/RsgSection.d.ts
fix the Error reported in the issue below 
https://github.com/vue-styleguidist/vue-styleguidist/issues/750
When searching with the option `tocmode: 'collapse'` the sections do not open automatically (because they keep their state).
The found section or page is therefore not visible nor clickable.
=> Fix: Open all sections when searching

docs/Thirdparties.md
Adding Theme UI to the docs addresses these two issues that I had yesterday:
1. Not finding in the first minutes why Styleguidist was not recognizing Theme UI was above all, a SEO issue: Theme UI is not mentioned in the docs, so you never get to Thirdparties through Google.
2. Once you end up in Thirdparties through the Styleguidist website, you are just going to bypass the "Adding styled-components ThemeProvider" section if your head didn't click yet about the facts that a) you are not passing the ThemeProvider to Styleguidist and b) Theme UI was built with Emotion among other technologies.
=> Adding Theme UI to Thirdparties docs

src/client/rsg-components/Props/Props.spec.tsx, src/client/rsg-components/Props/PropsRenderer.tsx, src/client/rsg-components/Props/renderDefault.tsx, src/client/rsg-components/Props/renderExtra.tsx, src/client/rsg-components/Props/renderType.tsx, src/client/rsg-components/Props/util.ts, src/client/rsg-components/Usage/Usage.tsx
Resolve
- Property types don't show up #1551
I organize react-docgen prop type(Named `PropDescriptor`) to have `flowType` and `tsType` both and I remove "WithFlow" word from the types.
review me please.
=> Fix Property types don't show up

src/client/rsg-components/TableOfContents/TableOfContents.spec.tsx, src/client/rsg-components/TableOfContents/TableOfContents.tsx
Resolved.
- Sections with href are always opening in new tabs #1559
The section does not open in the new tab unless `href` and `external` has set both.
please review me.
=> Fix Sections with href are always opening in new tabs

src/scripts/make-webpack-config.ts
Was still using an option that no longer exists. Fixed to mimic the original behavior. The option `root` was [removed in v2](https://github.com/johnagan/clean-webpack-plugin/issues/106) but [this commit](https://github.com/styleguidist/react-styleguidist/commit/98042591dc75cad8cdf88cc2a2f0817d69e5e66d) forgot to address it.
It's deleting everything in the `styleguidistDir` folder which isn't the way it was before.
With this PR, it only deletes files in `build/`.
=> Fix usage of CleanWebpackPlugin

src/client/utils/__tests__/transpileImports.spec.ts, src/client/utils/rewriteImports.ts
Resolve:
- Crash with some rewritten imports #1566
After the change, the relative path will split by `/` then joins by `_`.
For example, if gives `./cat/capybara/hamster`, it will be `dot_cat_capybara_hamster`.
Please review me.
=> Fix Crash with some rewritten imports

src/client/rsg-components/Props/Props.spec.tsx, src/client/rsg-components/Props/renderExtra.tsx
In `ef4c109b`, the file `PropsRenderer.js` (located at
`src/client/rsg-components/Props/PropsRenderer.js`) was removed. In
`PropsRenderer.js`, the `renderExtra` method checked whether `getType`
for the argument to `renderExtra` was present:
```es6
function renderExtra(prop) {
const type = getType(prop);
if (!type) {
return null;
}
...
}
```
However, in `ef4c109b`, this method was replaced with `renderExtra.tsx`
and the condition was changed to:
```typescript
export default function renderExtra(prop: PropDescriptorWithFlow): React.ReactNode {
const type = getType(prop);
if (!prop.type || !type) {
return null;
}
```
Unfortunately, this extra condition has resulted in this method always
returning `null` for a Flow typed prop as `prop.type` is always `null`
as `prop.type` is never set.
This …
=> Fix missing FlowType enum values in prop description

src/client/utils/__tests__/getInfoFromHash.spec.ts, src/client/utils/getInfoFromHash.ts
Resolve:
- Sections with numbers in the name don't work #1594
The main reason is that `parseInt` parses the first number string as a number.
Therefore, when `1.Doc` given, it was computed as `1`.
=> Fix Sections with numbers in the name don't work

package-lock.json, package.json
Update webpack-dev-server to version 3.11.1, which uses version 0.19.2 of http-proxy-middleware, which uses version 1.18.1 of http-proxy, as version 1.18.0 is vulnerable to Denial of Service, as advised: https://www.npmjs.com/advisories/1486
=> Update webpack-dev-server - vulnerable dependency

src/client/rsg-components/Props/Props.spec.tsx, src/client/rsg-components/Props/renderExtra.tsx
Let's treat `PropTypes.exact` the same way we treat `PropTypes.shape`. That is, show their constituent properties in Styleguidist. 
(Noob open-source contributor, sorry if I missed something. I tested this with the basic example, but didn't add any tests for it in code.)
=> Treat exact props the same as shape

examples/sections/styleguide.config.js, src/client/rsg-components/Argument/Argument.spec.tsx, src/client/rsg-components/Argument/ArgumentRenderer.tsx, src/client/rsg-components/Props/Props.spec.tsx, src/client/rsg-components/ReactComponent/ReactComponent.spec.tsx
Doctrine has a function to stringify the parameter types. If the type is a `string[]`, doctrine will stringify this into `Array.<string>`. I believe this is backwards compatible.
=> Fix param of array

site/src/plugins/goatcounter-plugin.js
When using e.g. uBlock Origin, navigation in the styleguidist documentation is broken. This is because in that case "window.goatcounter" is undefined. I added a check that assures, goatcounter.count will only be called if goatcounter is defined. This way clicking on links and navigating the documentation still works when goatcounter is blocked.
=> Fix: Fix site links for adblock users

examples/sections/styleguide.config.js, package-lock.json, package.json, src/client/rsg-components/ComplexType/ComplexType.spec.tsx, src/client/rsg-components/ComplexType/ComplexTypeRenderder.tsx, src/client/rsg-components/ComplexType/index.ts, src/client/rsg-components/Props/Props.spec.tsx, src/client/rsg-components/Props/renderType.tsx, src/client/rsg-components/Tooltip/Tooltip.spec.tsx, src/client/rsg-components/Tooltip/TooltipRenderer.tsx, src/client/rsg-components/Tooltip/index.ts, src/typings/dependencies/react-docgen.ts
Resolved:
- Wrong union description with TypeScript #1621
Main changes:
- Create a new component named `ComplexType` and `Tooltip` to show the complex type
- Introduce [tippyjs-react](https://github.com/atomiks/tippyjs-react) in the project
- ~~Add styleMock in the test assets to mock CSS import~~
Hover Actions:
Keyboard Actions:
(use Tab key)
=> Fix Wrong union description with TypeScript #1621

docs/Webpack.md
Hi 👋🏽 
First off, thanks for all the work on this project, really love it!
I thought it would be helpful to add a section that addresses how to configure react-styleguidist with Next.js specifically. With the pre-existing information in the webpack docs it's possible to configure, but I thought given how popular Next.js is it warranted a reference to make it more accessible. I'd also be down to adding an example project if need be. Feel free to disregard otherwise
Cheers!
=> Added Next.js configuration info to docs

src/loaders/__tests__/examples-loader.spec.ts, src/loaders/examples-loader.ts, src/loaders/utils/resolveESModule.ts
Fixes: https://github.com/styleguidist/react-docgen-typescript/issues/292
With react-docgen-typescript's version 1.20.4, components with `@visibleName` JSDoc tags are working. However, it changes the react component's `displayName` to the one specified in `@visibleName`, and when it contains a `.`, the code examples were not working. This was because Styleguidist was trying to import the component with the dot in its name in the code example which resulted in the syntax error.
Example:
```tsx
// ===== DialogTitle.tsx ======
/**
* @visibleName Dialog.Title
*/
export const DialogTitle = props => (<h2 {...props} />);
// ===== Dialog.tsx ======
import DialogTitle from './DialogTitle.tsx';
const Dialog = ({ children }) => <div>{children}</div>;
Dialog.Title = DialogTitle;
export default …
```
=> Fix visibleName with dots

src/client/rsg-components/Argument/ArgumentRenderer.tsx, src/loaders/utils/__tests__/getProps.spec.ts, src/loaders/utils/getProps.ts
Resolved
- Warning in ArgumentRenderer #1667
I checked the behavior of the component of the original issue after I changed the `name` to optional and found that the following error occurred.
```
DoctrineError {name: "DoctrineError", message: "Unknown type undefined"}
```
What I have found in my research is that in the above cases, `type.type` in the `returns` is lost in `getProps` in this case.
`returns` should have `NameExpression` in `type.type` in my opinion.
```js
// I saw this shape.
{ 
description: 'return a Boolean Value', 
type: { name: 'boolean' } 
}
// but it should be this shape.
{
title: 'returns',
description: 'return a Boolean Value',
type: { type: 'NameExpression', name: 'boolean' }
}
```
=> Fix Warning in ArgumentRenderer #1667

src/client/rsg-components/Para/ParaRenderer.tsx
Resolved:
- #1661 
This image shows that I've changed the `fontSize.text` in the config.
config
```
module.exports = {
theme: {
fontSize: {
text: 36,
},
},
};
```
=> Fix Para components should use `theme.fontSize.text`

src/client/rsg-components/ComplexType/ComplexTypeRenderder.tsx
Resolved:
- #1723 
The steps to reproduce:
1. Use Firefox and TypeScript project
2. Run the styleguide and open the props & methods table
3. Open the dev-tool and modify the type name to something very long. (for example: `function` => `functionsdfakdshjaksdjfka`)
4. Reproduce 🎉 
Before the change:
After the change:
=> Fix Type description tooltip isn't spaced properly in Firefox

.github/workflows/node.js.yml, package.json, tsconfig.types.json
in version 11.1.5 when we moved to Github Actions we added a dangerfile.ts to the tsconfig.json
This file, since it is outside the src folder, changed the reference rootFolder for typings to calculate.
This quick adjustment should fix the typings.
I also updated CI to have clearer action steps (where we can measure progress from a high level).
Cypress 3.0.2 does not seem to work well with the Linux version on the github action docker images.
=> fix: generate typings directly in lib instead of lib/src

site/src/pages/learn.js
Seems that Component-Driven have change the domain name from `.io` to `.dev`, and the original domain name is not accessible now.
=> Fix Component Driven Domain

docs/Development.md
The source code was migrated to typescript but this link wasn't updated so it is a 404 on this page:
https://react-styleguidist.js.org/docs/development/#webpack-loaders-and-webpack-configuration
=> docs: fix link to webpack config

.github/workflows/node.js.yml
Reference: https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
=> ci(node.js): add npm 'cache' to node.js workflow
