package.json
:rocket:
One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.
You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.
Have a good day!
---
This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.
<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>
=> Updated react-docgen to version 2.2.0

package.json
:rocket:
One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.
You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.
Have a good day!
---
This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.
<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>
=> Updated glob to version 5.0.15

Readme.md, loaders/styleguide.loader.js, src/components/Components/Components.js, src/components/Editor/Editor.js, src/components/Playground/Playground.js, src/components/Props/Props.js, src/components/ReactComponent/ReactComponent.js, src/components/StyleGuide/StyleGuide.js, src/index.js, src/utils/config.js
This is my first time using Webpack so not sure if this is the best way to do it but it does work.  Let me know if any changes need to be made.
=> Add CodeMirror syntax theme support

Readme.md
I find the current README hard to read because there is so much white space and the page is so long. This PR is my approach to improve readability.
You can see how it looks like at https://github.com/lovelybooks/react-styleguidist/blob/readme-formatting/Readme.md
=> Nicer formatting for the README documentation.

src/components/Props/Props.js
=> Fix for #13

loaders/styleguide.loader.js, src/components/Layout/Layout.css, src/components/ReactComponent/ReactComponent.css, src/components/ReactComponent/ReactComponent.js
Looks like this:
The shown path is relative to `config.rootDir`.
=> Added "defined in file ..." information for the components.

package.json
=> Upgrade react-docgen to support stateless React components

src/components/Components/Components.js, src/components/Layout/Layout.js, src/components/Playground/Playground.js, src/components/Preview/Preview.js, src/components/ReactComponent/ReactComponent.js, src/components/StyleGuide/StyleGuide.js, src/index.js, src/make-webpack-config.js
Fixes: #42 
I have tested the examples and ran the tests, but please make sure that things seems okay before merging.
Kind regards
Sune
=> Unique alias for components to avoid conflicts with host projects

.gitignore, package.json, src/make-webpack-config.js
=> Issue 59 fix

src/rsg-components/Layout/Layout.css
Layout was broken when there was some wide component. This little change fixes this.
=> Layout fix

Readme.md
Most important change is the more streamlined installation instruction. I also changed formatting in a few places, added a few badges, links, and stuff.
See it with formatting: https://github.com/sapegin/react-styleguidist/tree/readme-update
=> Updated the README.

src/rsg-components/TableOfContents/TableOfContents.css, src/rsg-components/TableOfContents/TableOfContents.js
Add fuzzy search to Table Of Contents
=> Add fuzzy search to Table Of Contents

package.json
Contributes to potentially closing #116
=> Update babel-preset-react-hmre to v1.1.1

src/make-webpack-config.js
=> Regexp to match windows path separators

package.json, src/make-webpack-config.js, src/utils/config.js
This should support webpack 2 out of the box.
Fixes #146
=> Support webpack 2

src/rsg-components/Examples/Examples.js
=> Fix prop warning for markdown text

Readme.md
=> Update rumble-charts link

src/rsg-components/Preview/Preview.js
=> Add missing objectAssign option to buble transform

src/rsg-components/ReactComponent/ReactComponentRenderer.js, src/rsg-components/ReactComponent/ReactComponentRenderer.spec.js
=> Fix: Do not display Props heading and section when no props are defined.

package.json
To avoid a peer dep warning :)
=> Add webpack 2.2 support in peer deps

src/rsg-components/ReactComponent/ReactComponent.js
Fixes some components displaying empty table of public methods (https://github.com/styleguidist/react-styleguidist/pull/280#issuecomment-271347351)
=> Fixes empty public methods

package.json, src/index.js, src/rsg-components/Preview/Preview.js
Previewing components doesn't work in IE 11 so added es6-object-assign polyfill.
=> Added es6-object-assign polyfill

package.json, src/index.js, src/rsg-components/StyleGuide/StyleGuideRenderer.js
=> Adds support for IE11 

loaders/__tests__/props-loader.spec.js, loaders/utils/getProps.js, test/components/Placeholder/Placeholder.js
=> Fix JSDoc tags in component descriptions breaking build

docs/GettingStarted.md
I found it confusing to show this snippet without the content from the previous step, so suggest showing it integrated.
=> Show content recommended in previous step

src/rsg-components/Heading/HeadingRenderer.js, src/rsg-components/Heading/__snapshots__/Heading.spec.js.snap, src/rsg-components/ReactComponent/ReactComponent.spec.js, src/rsg-components/Section/__snapshots__/Section.spec.js.snap
=> Move navigation ids from anchors to headings

examples/basic/src/components/Button/Button.js, src/rsg-components/Props/Props.spec.js, src/rsg-components/Props/PropsRenderer.js, src/rsg-components/Props/__snapshots__/Props.spec.js.snap, src/styles/theme.js
=> Hide function sources for PropType.func

package.json, scripts/__tests__/create-server.spec.js, scripts/__tests__/index.spec.js, scripts/make-webpack-config.js, yarn.lock
=> Hash JS assets in production build

src/rsg-components/Examples/Examples.spec.js, src/rsg-components/Message/Message.spec.js, src/rsg-components/Message/__snapshots__/Message.spec.js.snap, src/rsg-components/Playground/Playground.spec.js, src/rsg-components/Props/Props.spec.js, src/rsg-components/Props/__snapshots__/Props.spec.js.snap, src/rsg-components/Sections/Sections.spec.js, src/rsg-components/Sections/__snapshots__/Sections.spec.js.snap, src/rsg-components/StyleGuide/StyleGuide.spec.js, src/rsg-components/StyleGuide/__snapshots__/StyleGuide.spec.js.snap
Added some tests for the `rsg-components`. Most of them are snapshot tests.
=> Added some tests

src/rsg-components/ExamplePlaceholder/ExamplePlaceholderRenderer.js, src/rsg-components/ExamplePlaceholder/__snapshots__/ExamplePlaceholder.spec.js.snap
Adds Server Warning and removes background from link
=> Add Server restart warning when no Readme.md file is present

src/rsg-components/ComponentsList/ComponentsListRenderer.js, src/rsg-components/Heading/HeadingRenderer.js, src/rsg-components/Logo/LogoRenderer.js, src/rsg-components/Markdown/Markdown.js, src/rsg-components/Methods/MethodsRenderer.js, src/rsg-components/Playground/PlaygroundRenderer.js, src/rsg-components/Props/PropsRenderer.js, src/rsg-components/ReactComponent/ReactComponentRenderer.js
This styles react-styleguidist components with the user's configured theme colour.
=> Add theme colour to rsg components

loaders/props-loader.js, loaders/utils/__tests__/__snapshots__/getProps.spec.js.snap, loaders/utils/__tests__/getProps.spec.js, loaders/utils/getProps.js
I had to do some massaging to get the example file to resolve to the correct directory but you might have an easier way to do it.
=> Check Example File Exists

scripts/make-webpack-config.js
Fixes #499. The warning looks like:
=> Added deprecation warning for Webpack 1

examples/customised/styleguide/components/Logo.js
I found it confusing when I started playing with this example.
=> Update Logo.js example

docs/Configuration.md, loaders/examples-loader.js, loaders/utils/__tests__/chunkify.spec.js, loaders/utils/chunkify.js, src/rsg-components/Playground/Playground.js, src/rsg-components/Playground/Playground.spec.js
https://github.com/styleguidist/react-styleguidist/issues/269
https://github.com/styleguidist/react-styleguidist/issues/517
=> examples preprocessor and case insensitive settings for example

src/index.js
=> Dynamically update document.title when switching to isolated mode

docs/Webpack.md
"our of the box" -> "out of the box"
=> Correct typo

src/styles/nonInheritedProps.js, src/styles/setupjss.js
=> Set line-height to inherit

src/rsg-components/Preview/Preview.js
Fixing #545 - Preview not updating when initialState is edited in code-editor
=> fix(Preview): Preview not updating when initialState is edited in code-editor

src/rsg-components/Section/Section.js, src/rsg-components/Section/Section.spec.js, src/rsg-components/Section/SectionRenderer.js, src/rsg-components/Section/__snapshots__/Section.spec.js.snap, src/rsg-components/Sections/Sections.js, src/rsg-components/Sections/Sections.spec.js, src/rsg-components/Sections/__snapshots__/Sections.spec.js.snap, src/rsg-components/StyleGuide/StyleGuide.js, src/rsg-components/StyleGuide/__snapshots__/StyleGuide.spec.js.snap
=> Fix: Only use primary style for top level sections (#554)

docs/Configuration.md
Adds extra example to `updateExample()` as discussed in #560
=> docs: adding static setting injection example to updateExample()

src/styles/__tests__/createStyleSheet.spec.js, src/styles/createStyleSheet.js
Fix #566
Abandoned last pull request and created a new one, including a test, and with a different commit commit message to match your pattern ;P
=> Fix: Support config theme overriding top level theme properties (#566)

package-lock.json, package.json, src/rsg-components/Editor/Editor.js, src/rsg-components/Editor/Editor.spec.js, src/rsg-components/Editor/__snapshots__/Editor.spec.js.snap, src/rsg-components/Playground/Playground.spec.js
=> Migrate to react-codemirror2

docs/Configuration.md, loaders/__tests__/examples-loader.spec.js, loaders/examples-loader.js
https://github.com/styleguidist/react-styleguidist/issues/579
=> feat(*): pass exampleFilePath to update example

docs/Cookbook.md
Just trying to figure out styling and figured it might help...
=> More explicit detail and grammar

package-lock.json, package.json
Update React Docgen for support of the new Flow 0.53 annotations:
https://github.com/reactjs/react-docgen/pull/209
=> Support new flow 0.53 annotations

package-lock.json, package.json
Upgrade dependencies to get rid of warnings about React 16.
#614
=> upgrade react-codemirror2

docs/Thirdparties.md
=> Docs: Add Styletron example

package-lock.json, package.json
=> (chore): Removes react-addons-test-utils

examples/basic/src/components/Button/Button.js, examples/basic/src/components/Button/Readme.md
Fix prop type warning on console.
=> fix invalid prop type warning

docs/Documenting.md
Correcting an error I introduced in PR #642
=> Correct the `static` modifier note

package-lock.json, package.json
=> Remove unused "webpage" dependency

src/styles/setupjss.js
Related to: https://github.com/styleguidist/react-styleguidist/issues/652
Feedback appreciated :)
=> Fix: Inherit color (#652)

Readme.md
As suggested here by @sapegin: https://github.com/styleguidist/react-styleguidist/issues/464#issuecomment-342114531
=> Add Yammer to showcase list

src/rsg-components/slots/CodeTabButton.js
Simple update to change "Code" into "View Code" - this was a major pain point for non-dev trying to see the code of our examples. Fixes #693
=> feat: minor content update (View Code instead of Code)

docs/Thirdparties.md, loaders/__tests__/props-loader.spec.js, loaders/__tests__/styleguide-loader.spec.js, loaders/utils/__tests__/__snapshots__/getSections.spec.js.snap, loaders/utils/__tests__/getComponentFiles.spec.js, package-lock.json, package.json, scripts/schemas/config.js, test/components/Annotation/Annotation.js
=> feat: Add JSDoc @component annotation support

docs/Cookbook.md
This PR replaces missing Storybook gif in cookbook with a new one.
=> Fix Storybook GIF

src/rsg-components/Markdown/List/List.spec.js, src/rsg-components/Markdown/List/ListRenderer.js, src/rsg-components/Markdown/List/__snapshots__/List.spec.js.snap, src/rsg-components/Markdown/List/index.js, src/rsg-components/Markdown/Markdown.js, src/rsg-components/Markdown/__snapshots__/Markdown.spec.js.snap
Relates to Issue #613 and #619
=> Feat: Introduce List components for Markdown.

package-lock.json, package.json
This fixes #783 because version `1.1.5` of the plugin pins the `uglify-es` version to one without the bug.
=> Update uglifyjs-webpack-plugin to 1.1.5

package-lock.json, package.json
Decrease `buble` verison to `0.16.0` to fix https://github.com/styleguidist/react-styleguidist/issues/798
I also created an issue - https://github.com/Rich-Harris/buble/issues/104
=> Decrease buble version

.eslintrc, .gitignore, .travis.yml, cypress.json, cypress/fixtures/example.json, cypress/integration/initial_spec.js, cypress/plugins/index.js, cypress/support/commands.js, cypress/support/index.js, package-lock.json, package.json, test/run.server.js
Hi, 
this PR is an attempt of first step for issue #776 
It includes cypress setup, new npm scripts and one simple test. I've left most of the cypress scaffolded files, since it can be a good reference for other contributors.
Currently, cypress tests can not be run fully automatically, so first you need to start a test server (`test:cypress:runTestServer`) and than either run the cypress GUI (`test:cypress:open`) or run the tests from command line (`test:cypress:run`).
I have reused the server from `run.server.js`, but changed the port to 8082 so the tests can be run in parallel with default port styleguidist instance.
Would love to get some feedback and maybe a little better understanding where do you see cypress tests fit for this project. Do you want them to run together with other …
=> feat: setup cypress

src/rsg-components/Markdown/Blockquote/Blockquote.spec.js, src/rsg-components/Markdown/Blockquote/BlockquoteRenderer.js, src/rsg-components/Markdown/Blockquote/__snapshots__/Blockquote.spec.js.snap, src/rsg-components/Markdown/Blockquote/index.js, src/rsg-components/Markdown/Markdown.js, src/rsg-components/Markdown/Markdown.spec.js, src/rsg-components/Markdown/__snapshots__/Markdown.spec.js.snap
So that it is easier for consumers to customize their styleguide by replacing
components.
=> Introduce markdown Blockquote component. #613

scripts/make-webpack-config.js
To have webpack 4 configured correctly we need to set
the webpack mode.
=> fix: configure webpack 4

docs/Thirdparties.md
This PR adds a tiny note to documentation about making RSG work with react-css-themr.
=> Add a note about working with react-css-themr

bin/styleguidist.js
=> More user-friendly message for the EADDRINUSE error

docs/Configuration.md, docs/Webpack.md, scripts/utils/__tests__/mergeWebpackConfig.spec.js, scripts/utils/mergeWebpackConfig.js
This PR fixes #937 and improves the appropriate test.
=> Fix: Ignore mini-html-webpack-plugin

scripts/make-webpack-config.js
Related to developit/preact#1065
=> Add `reduce_funcs: false` to uglify for preact compatibility

docs/Configuration.md, scripts/schemas/config.js
I am sorry for that, I was about to sleep and noticed my mistake :)
=> Fix: serverPort can't be string

docs/Maintenance.md
Feel free to comment and ask more questions if anything isn't clear.
=> Add Maintainter guide

package-lock.json, package.json
https://github.com/styleguidist/react-styleguidist/issues/986
=> feat(*): up react-docgen

src/rsg-components/Heading/HeadingRenderer.js
=> made h5 bold and h6 italic

package-lock.json, package.json, src/rsg-components/Playground/__snapshots__/Playground.spec.js.snap, src/rsg-components/ReactComponent/__snapshots__/ReactComponent.spec.js.snap, src/rsg-components/StyleGuide/__snapshots__/StyleGuide.spec.js.snap, src/utils/__tests__/__snapshots__/renderStyleguide.spec.js.snap
We need upgrade jest to 23 for mock module in https://github.com/styleguidist/react-styleguidist/pull/1034
=> chore(*): up to jest 23

src/rsg-components/Props/Props.spec.js, src/rsg-components/Props/PropsRenderer.js, src/rsg-components/Props/__snapshots__/Props.spec.js.snap, src/rsg-components/Props/util.js
https://github.com/styleguidist/react-styleguidist/issues/1032
=> fix(*): fix flow union props rendering

src/index.js
https://github.com/styleguidist/react-styleguidist/issues/1025
=> chore(*): remove validation of rsg container id

src/rsg-components/Editor/Editor.js, src/rsg-components/Editor/Editor.spec.js, src/rsg-components/Editor/EditorLoaderRenderer.js
Fix: #1047
CodeMirror styles moved to Editor component.
=> Isolate CodeMirror styles

package-lock.json, package.json
...because `react-docgen-displayname-handler` has it as a peerDependency
=> Add explicit recast dependency

src/rsg-components/Playground/Playground.js, src/rsg-components/Playground/__snapshots__/Playground.spec.js.snap
=> Fix: restoring support for evalInContext for custom slots (#1067)

package.json, test/cypress/integration/core_spec.js
- Fix deploy (https://github.com/styleguidist/react-styleguidist/commit/e988f3e525e780824573382e9876ab2eeb395963)
=> fix: Cypress failing test

docs/Cookbook.md
=> fix: correct cookbook dynamically load other components

src/rsg-components/slots/index.js
=> slots components path changes

src/rsg-components/Props/util.js
sometimes the value is null and replace throws an error.
=> fix for null in replace

examples/react-native/.babelrc, examples/react-native/package-lock.json, examples/react-native/package.json
=> Examples: updated react-native example to use Babel 7 targets

src/rsg-components/Name/NameRenderer.js, src/rsg-components/Name/__snapshots__/Name.spec.js.snap, src/rsg-components/Type/TypeRenderer.js, src/rsg-components/Type/__snapshots__/Type.spec.js.snap
=> Removed <Code> styles from Name and Type renderers

package-lock.json, package.json
=> Chore: update webpack-dev-server due to vulnerability

package-lock.json, package.json, src/client/rsg-components/Argument/ArgumentRenderer.js, src/client/rsg-components/Argument/__snapshots__/Argument.spec.js.snap, src/client/rsg-components/Props/PropsRenderer.js, src/client/rsg-components/Props/__snapshots__/Props.spec.js.snap
Closes #1265 
First contribution to open source ever :)
=> Upgrade react-group to v3 

src/bin/styleguidist.js
=> Fix: kleur is not a function

package-lock.json, package.json
Fixes: https://github.com/styleguidist/react-styleguidist/issues/1290#issue-414901070
=> Update clipboard copy package

.github/Contributing.md
Closes https://github.com/styleguidist/react-styleguidist/issues/1303
=> Update introductions for compiling and starting server to separate terminals

src/loaders/utils/client/requireInRuntime.js
=> typo(comment): text

src/client/index.js, src/client/rsg-components/slots/IsolateButton.js, src/client/rsg-components/slots/__snapshots__/IsolateButton.spec.js.snap
Just a small PR to center the view on the section was viewing when leaving the isolated mode.
=> feature(scroll): Scroll section in to view when exiting isolated view

examples/sections/babel.config.js, examples/sections/package-lock.json, examples/sections/package.json
Updated package.json libraries in sections example.
Example was showing this error
```
FAIL  Failed to compile
./src/components/Placeholder/Placeholder.js
Module not found: Can't resolve 'core-js/modules/es7.symbol.async-iterator' in '/home/jorgeortega/GitHub/react-styleguidist/examples/sections/src/components/Placeholder'
./src/components/RandomButton/RandomButton.js
Module not found: Can't resolve 'core-js/modules/es7.symbol.async-iterator' in '/home/jorgeortega/GitHub/react-styleguidist/examples/sections/src/components/RandomButton'
```
=> Update examples/sections libraries to latest versions

src/client/rsg-components/ComponentsList/ComponentsList.js, src/client/rsg-components/ComponentsList/ComponentsListRenderer.js, src/client/rsg-components/ComponentsList/__snapshots__/ComponentsList.spec.js.snap
=> Render sections with href in sidebar

docs/Cookbook.md
This list was really helpful! An active/inactive distinction seems pretty clear... but beyond that which tool is best for the job gets much more subjective.
=> Distinguish active projects from inactive

examples/basic/src/components/Button/Readme.md, src/client/rsg-components/ReactExample/ReactExample.js, src/client/rsg-components/ReactExample/ReactExample.spec.js
Implements the proposed solution for #1343
=> Support React Hooks in examples

examples/styled-components/babel.config.js, src/client/rsg-components/Examples/Examples.js, src/client/rsg-components/Examples/ExamplesRenderer.js, src/client/rsg-components/Examples/__snapshots__/Examples.spec.js.snap, src/client/rsg-components/Playground/Playground.js, src/client/rsg-components/Playground/Playground.spec.js, src/client/rsg-components/Playground/PlaygroundRenderer.js, src/client/rsg-components/Playground/__snapshots__/Playground.spec.js.snap, src/client/rsg-components/ReactComponent/ReactComponentRenderer.js, src/client/rsg-components/ReactComponent/__snapshots__/ReactComponent.spec.js.snap, src/client/rsg-components/StyleGuide/StyleGuideRenderer.js, src/client/rsg-components/StyleGuide/__snapshots__/StyleGuide.spec.js.snap, src/client/rsg-components/ToolbarButton/ToolbarButtonRenderer.js, src/client/rsg-components/slots/IsolateButton.js, src/client/rsg-components/slots/__snapshots__/IsolateButton.spec.js.snap, test/cypress/integration/component_spec.js, test/cypress/integration/core_spec.js
Some work towards https://github.com/styleguidist/react-styleguidist/issues/776
=> Add more Cypress tests for isolated mode toggling

flow-typed/estree-walker.js.flow, package-lock.json, package.json, src/client/utils/transpileImports.js, src/loaders/utils/getImports.js
@sapegin could you please look at this PR and check if this is acceptable?
I'm concerned that this might break existing functionality, as the AST walking is a core part of the code, and the implemented code technically breaks the tests, however, this seems to be a popular fix, so opening this up for further discussion
Fixes #1210
=> Chore: Replace 'walkes' with 'estree-walker'

src/scripts/make-webpack-config.js
Fixes https://github.com/styleguidist/react-styleguidist/issues/1385
=> Update resolve.extensions in webpack config

docs/Configuration.md
=> Change "value may depends" to "value may depend"

src/client/rsg-components/ComponentsList/ComponentsList.spec.js, src/client/rsg-components/ComponentsList/ComponentsListRenderer.js
Fix with IF condition. Check if routing is based on flat or sectioned system.
=> Fix #1375 - Highlighting currently selected page on sidebar broken with sections

docs/Documenting.md, docs/Webpack.md, examples/sections/src/ThemeContext.js, examples/sections/src/components/ThemeButton/Readme.md, examples/sections/src/components/ThemeButton/ThemeButton.css, examples/sections/src/components/ThemeButton/ThemeButton.js, examples/sections/src/components/ThemeButton/index.js, examples/sections/styleguide.config.js
It's not perfect, but it is a start.
=> Resolves #1374 - Provide example of using context

examples/basic/babel.config.js, examples/basic/package-lock.json, examples/basic/package.json
Update package.json and babel config to fix #1410. I received the same error as #1340 when I tried to reproduce #1410 in the basic example. I did a similar fix to #1340 and it was resolved.
=> #1410 Update package.json in basic example to fix error

.travis.yml, babel.config.js, package-lock.json, package.json
=> chore: drop node 6

docs/CLI.md, docs/Configuration.md, src/bin/styleguidist.js, src/scripts/schemas/config.js
This PR adds the ability to specify the serverPort via cli and fixes #936
=> Feat: Add serverPort command line option

docs/Configuration.md, docs/Cookbook.md, examples/customised/styleguide.config.js, src/client/rsg-components/Styled/Styled.tsx, src/client/styles/__tests__/createStyleSheet.spec.ts, src/client/styles/createStyleSheet.ts, src/scripts/schemas/config.ts, src/typings/RsgStyles.d.ts, src/typings/StyleguidistConfig.d.ts
=> New: Accept styles config as a function

docs/Configuration.md
When I added the cookbook item for tocMode, I forgot to update the table of contents.
That is called irony I believe.
=> Docs: Update TOC of configuration

src/loaders/utils/__tests__/highlightCode.spec.ts, src/loaders/utils/highlightCode.ts
Hello, guys!
Do you mind about the "less" syntax highlighting support?
=> New: “less” syntax highlighting

src/client/utils/getRouteData.ts
Example with targetIndex = 0 was not shown
=> fix zero example

package-lock.json, package.json
Resolved:
- Update Buble to v20 #1659
Please review me.
=> Bump buble from 1.19.8 to 0.20.0

docs/Cookbook.md
=> Update cookbook documentation on CSS animation usage

src/client/utils/__tests__/processSections.spec.ts, src/client/utils/processSections.ts
Resolved:
- Links don't work anymore for `pagePerSection` #1702
=> Fix Links don't work anymore for `pagePerSection`

package-lock.json, package.json, src/scripts/make-webpack-config.ts
resolves #1714 #1705 
- Fix based on advice from @lyz810
- Tested locally the issue is fixed (able to reproduce the bug by reverting the fix)
=> fix devServer crash
